### ISSUE TITLE
Fetch data from repository models

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#11]
Configured data sets grouped by section.

**Comment by akmiller01** [comment]
https://github.com/devinit/ddw-analyst-ui/pull/59

**Comment by akmiller01** [comment]
@Napho I think this is our next critical step. #59 should handle the fetching of data sources, but now we need to use the sources from that PR to fetch the actual data.

**Comment by akmiller01** [comment]
In progress and partially done with https://github.com/devinit/ddw-analyst-ui/pull/61

**Comment by akmiller01** [comment]
We just need a little bit of logic that sends the `feature/pypika` `Operation.build_query()` queries to the `datasets` data models.
