### ISSUE TITLE
No source table for Source Update History

### ISSUE THREAD

**Issue by Napho** [devinit/ddw-analyst-ui#112]
Update history table is available as a UI component but there is no database table keeping track of the updates.

**Comment by k8hughes** [comment]
Do we know if this is still the case today? @wakibi and @edwinmp ?

**Comment by edwinmp** [comment]
@k8hughes this is done & is good to close
![image](https://user-images.githubusercontent.com/5672438/116054910-db4bbd80-a684-11eb-8bf1-165dd766a849.png)
