### ISSUE TITLE
Adding the DI logo

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#113]
Anna suggested that we make the tool DI branded which is a sign of approval :)

@edwinmp do you have the logo file?  Are you happy to work out where it should go etc?

**Comment by edwinmp** [comment]
haha ... all the red was enough I guess :) Will add a favicon and one on the top left ... just the `DI` should do.

**Comment by edwinmp** [comment]
@k8hughes I'm hoping this is enough ... 

![image](https://user-images.githubusercontent.com/5672438/58266739-f459de80-7d8a-11e9-9c30-75dacd2bc37d.png)

**Comment by k8hughes** [comment]
I like that, it looks good.
