### ISSUE TITLE
Create staging

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#119]

**Comment by k8hughes** [comment]
Making sure that we have a staging version so we have a separate place for deploying bug fixes

**Comment by akmiller01** [comment]
Done: http://ddw.devinit.org:8080/

Currently deployed off of `staging-deployment` and run on docker-compose under the user `dev` in the folder `/home/dev/ddw-analyst-ui-staging`

There is also a convenience script at `/home/dev/docker_clone_volume.sh` that lets you clone from the `metadata` volume to the `metadatastaging` volume like so:

`./docker_clone_volume.sh metadata metadatastaging`

**Comment by edwinmp** [comment]
@akmiller01 is this running on the same server as the production instance?

**Comment by akmiller01** [comment]
Yes.
