### ISSUE TITLE
Manual datasets for upload

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/ddw-analyst-ui#150]
Historical_income_groupings:

File has added a new year of data (2018) into the income groups file. 

Data attached here: [historical_income_groupings.xlsx](https://github.com/devinit/ddw-analyst-ui/files/4564405/historical_income_groupings.xlsx)

Should not be any changes to headings and the file name as compared to the information on the page here: https://github.com/devinit/ddw-analyst-ui/tree/master/data_updates/manual/CSV

**Comment by Duncan-Knox** [comment]
developing_countries:

Data attached here: [developing_countries.xlsx](https://github.com/devinit/ddw-analyst-ui/files/4729394/developing_countries.xlsx)

File has added new columns based on changes in developing country classifications.

**Comment by Duncan-Knox** [comment]
oecd_regions:

Data attached here: [oecd_regions.xlsx](https://github.com/devinit/ddw-analyst-ui/files/4729397/oecd_regions.xlsx)

File has added new columns based on changes in developing country classifications.

**Comment by Duncan-Knox** [comment]
Hi @akmiller01, all the files attached to the comments in this issue here are ready for upload. Not certain they made it on.

**Comment by akmiller01** [comment]
Hey Duncan, I'll make a PR for these today! This issue slipped by my notice until now! In the future, you can add me as an Assignee so I get notifications.

**Comment by Duncan-Knox** [comment]
Hi Alex, thanks. I'll add you as an assignee going forward.

**Comment by akmiller01** [comment]
PR for the three sets above: https://github.com/devinit/ddw-analyst-ui/pull/317

**Comment by akmiller01** [comment]
Merged to develop @Duncan-Knox , do you want to keep this issue open for future updates? Or just open a new one when there are some?

**Comment by Duncan-Knox** [comment]
Thanks @akmiller01. I'll close this issue.
