### ISSUE TITLE
Update Data Sources UI

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#182]
- Remove metadata sidebar
- Show table in full width
- Add actions column
   - Add a button for Metadata - on click, open modal with metadata content

**Comment by edwinmp** [comment]
@mariamiah could you please also add an actions button that navigates to a page containing all Queries created from a particular Data Source.

**Comment by edwinmp** [comment]
This was to be handled in issue #131 but since we'll only have `Queries`, we can do it here. But instead of `Queries`, name the button `Datasets`

**Comment by mariamiah** [comment]
okay
