### ISSUE TITLE
Audit trail

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#19]
Model audit logs in database, admin interface for monitoring.

**Comment by akmiller01** [comment]
Exploring how this can be done with Django signals here: https://github.com/devinit/ddw-analyst-ui/commit/d80983d179543d7004e7da2690084a8e37541917 Waiting on more solid models to test and merge...

**Comment by akmiller01** [comment]
Waiting for review https://github.com/devinit/ddw-analyst-ui/pull/58

**Comment by akmiller01** [comment]
#58 merged.
