### ISSUE TITLE
Incorporate Government Domestic Budget Data into the DDW

### ISSUE THREAD

**Issue by akmiller01** [devinit/ddw-analyst-ui#196]
Add domestic.csv to manual datasets, plus requisite metadata.

**Comment by k8hughes** [comment]
@akmiller01  Is this something where the data is available?

**Comment by akmiller01** [comment]
It's something from the old DDW. Worth asking whether it's still needed by analysts, I suppose.

**Comment by k8hughes** [comment]
@Duncan-Knox what are your thoughts on this?  Do we need this data and is it still being created?
