### ISSUE TITLE
API to download difference between current data and new data

### ISSUE THREAD

**Issue by wakibi** [devinit/ddw-analyst-ui#199]
We need to create an API to download the difference between the current data and the new data. The analysts can then work with this instead of the whole table

**Comment by k8hughes** [comment]
@wakibi do we still need this issue?

**Comment by wakibi** [comment]
I do not think, the freeze functionality should be ably handle this.

**Comment by edwinmp** [comment]
Using the freeze functionality for this feels like overkill ... also, a lot of these updates are automated, so unless we automate freezing a data source before it's updated, I don't see it working here. Do we actually have a way of returning the difference between an updated data source & a frozen one?

**Comment by wakibi** [comment]
Some of these have no unique columns that we can use to determine the changes, so it will not be easy. But for FTS for example, adding the year column is one of the ways Carina and her team can tell old data from new data. I am not sure what works for the rest of the data

**Comment by edwinmp** [comment]
Ah, that's the context that was missing ... that this was targeting FTS tables. Those mostly have a relatively small number of rows, so I guess with some manual bits, the freeze feature could be used to catch changes. I don't see a use case outside of the FTS.

**Comment by wakibi** [comment]
Yes, it was FTS. Unless there is another use case outside FTS, I think we are okay closing this (or turning it into a discussion instead)
