### ISSUE TITLE
Set up Frontend development environment

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#2]
Webpack, react.
@edwinmp to add details.

**Comment by edwinmp** [comment]
Damn, more issues I missed. Guess we should have created a Dev Setup milestone.
Anyway, this is done... 

While it's all running on the Django engine, the application is split into an API accessible python (Django) backend, and a React frontend. The React dev environment is as below:

- Typescript: - dev language for its strictness. makes for better, less erroneous code.
- Webpack: - code bundler
- Grunt: - task runner
- Jest + React-Testing-Library: - unit tests
- Cypress: - end-to-end tests
- Bit: - react component management

**Comment by edwinmp** [comment]
Refer to pull request #51 for the related code
