### ISSUE TITLE
Paginated fetching of scheduled events & their run instances

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#206]
Currently, the scheduled events APIs fetch all records, which is not efficient for when we have a lot of records e.g. with run instances.
![image](https://user-images.githubusercontent.com/5672438/86235765-9f99b180-bba1-11ea-8dd0-990a5331af3e.png)

Solution is to paginate the API endpoints and fetch data by page

**Comment by wakibi** [comment]
I would suggest adding filters as well i.e completed, errored, pending, skipped

**Comment by edwinmp** [comment]
> I would suggest adding filters as well i.e completed, errored, pending, skipped

Yup, good idea ... create an issue for that please.
