### ISSUE TITLE
Create aliases for DDW tables to be used in the UI and exported files

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#215]

**Comment by edwinmp** [comment]
@akmiller01 could we use [this](https://github.com/devinit/ddw-analyst-ui/blob/develop/data_updates/manual/CSV/meta_columns.csv) for the aliases?
I've noticed that the majority of the entries under `col_description` are a formatted version of the column name, but not all, so we'd need another column for aliases.

**Comment by akmiller01** [comment]
Yes. Here's how they're loaded into the CMS: https://github.com/devinit/ddw-analyst-ui/blob/develop/data/management/commands/load_manual.py#L53-L57

It's up to the front-end on how to use col_name, col_source_name, and col_description differently.

**Comment by edwinmp** [comment]
@bill-anderson I added aliases to the DDW ... give it a try when you get a moment.

You can edit data column headers to create aliases
![image](https://user-images.githubusercontent.com/5672438/89865856-25ecde80-dbb7-11ea-8d09-e6ea675010b0.png)
Also `Export to CSV` produces an aliased CSV file

**Comment by bill-anderson** [comment]
Great.

I see someone has already replaced the "X_" with "Calculated". Could we put the " - Calculated" at the end. This will make it easier, for instance to find "sector" in its correct alphabetical order.

**Comment by akmiller01** [comment]
https://github.com/devinit/ddw-analyst-ui/pull/294
