### ISSUE TITLE
IATI transactions: descriptions of codes

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#216]
Can we hardwrite the following descriptions:
x_reporting_org_type
x_transaction_type
x_country
x_finance_type
x_aid_type
x_dac3_sector
x_di_sector (the itep aid bundle - mapped from x_dac3_code)

Codes are all here
[IATI DDW Codes.xlsx](https://github.com/devinit/ddw-analyst-ui/files/4884715/IATI.DDW.Codes.xlsx)

**Comment by akmiller01** [comment]
Done https://github.com/devinit/ddw-analyst-ui/commit/23e8a91616308b37844066c624501d6ebaa43154
