### ISSUE TITLE
User guidance

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#232]
We need a user manual - even if this is a gdoc that can be accessed from the main menu

**Comment by edwinmp** [comment]
Sure ... been making sure the new features come with plenty of built in help, but having documentation that compliments that will be really good.

**Comment by k8hughes** [comment]
It would make sense for this to be done by someone outside of the dev team I think, but that knows how to use the tool.  @bill-anderson lets discuss and see who we think could do this.

**Comment by bill-anderson** [comment]
If it was just a GDoc or something similar we could assign various people to cover different topics. I would be happy to write IATI guidance

**Comment by edwinmp** [comment]
At its simplest, I'm going to add a help button on each page that when clicked links to a google doc ... even if it starts out blank, anyone should be able to edit it as you would a wiki.

**Comment by k8hughes** [comment]
@bill-anderson could we use the IATI data manuel as a starting point?  do you have the link to this doc so far?

**Comment by bill-anderson** [comment]
https://docs.google.com/document/d/1rDR7yhyFEuT1PFbPEyBK2lkAuhqgEa6toOX1DdFDUEg/edit?usp=sharing

**Comment by k8hughes** [comment]
OK, looking at the IATI document it is already quite a big doc, so I think it is better to have a separate doc for the tool guidence - I have started a doc here:  https://docs.google.com/document/d/1j10m46dLY-zb5Mee4JWncTGeOsf2o8oChSN90ZUu8vk/edit

**Comment by k8hughes** [comment]
As we now have a base document I'm going to mark this as done, but we need to make sure it stays up to date as new features are developed.

**Comment by edwinmp** [comment]
https://github.com/devinit/ddw-analyst-ui/issues/470#issuecomment-829146519
