### ISSUE TITLE
Editing the SQL Query

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#234]
1. As I use the UI I would like to see the resulting SQL Query.
2. I would then (if I'm confident enough) like to edit the Query, rather than use the UI steps
3. And once I really know what I'm doing I would like to type the query without using the UI steps

**Comment by k8hughes** [comment]
I'll put this in the backlog - once we've finished work on the exisiting features we can do a bit of estimation on this then do a cost / benifit analysis

**Comment by edwinmp** [comment]
I'm going to close this in favour of #542 as it checks all the boxes here.
