### ISSUE TITLE
Limit size of export csv (no. of rows)

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#235]
If a query will return more than 1,048,575 rows (excel limit) it should be abandoned and the user should receive a message to rethink their query.

**Comment by k8hughes** [comment]
This one sounds like it would be useful to have especially now we are working with IATI data.  Moved to `to do`.

**Comment by edwinmp** [comment]
@davidebukali you seem to have worked on this at some point ... what happened?

**Comment by k8hughes** [comment]
@davidebukali Can you update this issue to say what work was done on this in the end?

**Comment by davidebukali** [comment]
@k8hughes @edwinmp the previous PR was closed because it could not scale for larger datasets (counting rows for each query and comparing with the limit). Adding a flag to the query to limit rows before they are returned is a pending fix.
