### ISSUE TITLE
Choice of filters limited after Select

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#236]
Once you have done a Select you can only add a filter based on columns selected. I should not have to display all the columns that I filter on.

**Comment by edwinmp** [comment]
This is not a bug @bill-anderson ... it's built this way, and we can't do it any other way ... each step is its own query, with each step being used as an input for the next one. So you'll have to do your filtering before the select.

**Comment by bill-anderson** [comment]
Noted
