### ISSUE TITLE
Confirmation before deleting a query

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#237]
Add a confirmation message before deleting a query.

(I have just deleted a whole query, thinking I was only deleting the step closest to the delete button)

**Comment by edwinmp** [comment]
@bill-anderson the delete buttons are a lot clearer now so you'll know what you're deleting, and they come with a confirmation. First click changes the button caption from `Delete` to `Confirm Delete` ... a second click deletes the item.
![image](https://user-images.githubusercontent.com/5672438/88808280-58f8a080-d1bb-11ea-9c76-d9c36c644efc.png)
