### ISSUE TITLE
Rename "Add Step" button in Step form

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#238]
In the Create Step form rename the "Add Step" button to "Save Step"
In this image the confusion between the different meaning of the two "Add Step" buttons is clear ...

![ddw1](https://user-images.githubusercontent.com/3491562/88272874-4967ec00-ccd1-11ea-9e7c-b7e45e9a7ce1.png)

**Comment by edwinmp** [comment]
@bill-anderson this change has been deployed.
![image](https://user-images.githubusercontent.com/5672438/88807906-e7b8ed80-d1ba-11ea-8360-d98f8ba7d783.png)
