### ISSUE TITLE
ETL - Default sector vocabulary

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#239]
We need to modify the logic here:
If Sector Vocab 1 is present then default = 1
If Sector Vocab 2 is present then default = 2
Otherwise determine the most used vocab

The reason for this is so that it is possible to filter on a single vocabulary AND always get DAC wherever possible

eg - iati-identifier XI-IATI-EC_ECHO-ECHO/-HF/BUD/2016/91022 which returns 99 although 1 is present.

(PS it is a modification not a bug but there is no appropriate label)

**Comment by akmiller01** [comment]
Done https://github.com/devinit/ddw-analyst-ui/pull/247/commits/e5af9c607c4cc6aad5d0d0affa4fa29b6060ebfe
