### ISSUE TITLE
ETL: New field: x_YYMM

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#240]
Realising that, both for filters and analysis it would be useful to have access to the transaction Month. (A lot of the charts on the tracker page will be focusing on monthly aggregates.) And YYMM would seem to be the most usable option.

**Comment by akmiller01** [comment]
We discussed nixing this column, right @bill-anderson ? Or did you still think it would be useful. In any event I would suggest YYYYMM just in case users want to sort it so 2020 (20) sorts above 1999 (99).

**Comment by bill-anderson** [comment]
Nope, we do need it. I'm happy with YYYYMM (though I'm not sure how relevant 1999 is to IATI or real-time data??)

**Comment by akmiller01** [comment]
https://github.com/devinit/ddw-analyst-ui/pull/247/commits/80051da3a2f228cbe38a8ef71e99179ee4d7842c
