### ISSUE TITLE
ETL: Should we hardcode Covid-related query?

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#241]
We can reproduce the IATI Covid guidelines in a Filter, but will we always do it accurately? Should we not add an x_Covid field: a Boolean that returns the result of the full query.
i.e.
```
Title contains “COVID-19” (or “COVID” or “coronavirus”)
or
Activity Description contains “COVID-19” (or “COVID” or “coronavirus”)
Or
Transaction contains “COVID-19” (or “COVID” or “coronavirus”)
or
Humanitarian Scope Code = “EP-2020-000012-001”
or
Humanitarian Scope Code = “HCOVD20”
or
Tag Code = “COVID-19”
```
https://docs.google.com/document/d/1hV_Bk2_VEQmrbSPbp3vE0Rho-gZtOJBSpLkOYInTnOY/edit#heading=h.gjdgxs

**Comment by akmiller01** [comment]
https://github.com/devinit/ddw-analyst-ui/pull/247/commits/80051da3a2f228cbe38a8ef71e99179ee4d7842c
