### ISSUE TITLE
Add google analytics to track usage

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#245]
Would be great not to have to ask the analysts what they use most, among other things.

**Comment by edwinmp** [comment]
@davidebukali where's the code to review for this?

**Comment by davidebukali** [comment]
@edwinmp most of the tracking was implemented on gtm manager with click events and tags. Once signed into gtm, all relevant events have DDW in their names.

**Comment by edwinmp** [comment]
Which analytics & tag manager accounts did you bind them to? Please invite me to them ... hopefully not the ones for the DI website.

**Comment by k8hughes** [comment]
was this set up to the right accounts in the end?

**Comment by davidebukali** [comment]
@edwinmp @k8hughes my apologies, this was set up in the website account. On the bright side, looks like its possible to [export/import](https://support.google.com/tagmanager/answer/6106997?hl=en) tags between containers. I can work on this as soon as I get access to analytics accounts for DDW

**Comment by edwinmp** [comment]
Created & shared the new analytics account & tag manager container ...

**Comment by k8hughes** [comment]
David to work on Edwin's feedback.

**Comment by edwinmp** [comment]
@davidebukali I don't find the event information satisfactory ... all the fields are `undefined`. Please make time and investigate.

**Comment by davidebukali** [comment]
@edwinmp google analytics script was missing in html, have added to this [PR](https://github.com/devinit/ddw-analyst-ui/pull/464)
