### ISSUE TITLE
Set certifcates to auto renew so SSL doesn't expire

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#248]
And details to go into the repo and passwords into one password.
Spotlights API is down currently.

**Comment by akmiller01** [comment]
The API is in this repo, and the SSL process is documented there now: https://github.com/devinit/ddw-external-api/tree/master

Good to close this @k8hughes ?

**Comment by k8hughes** [comment]
@edwinmp @davidebukali could you two both confirm you'd have the details we need if there were ever any issues with the SSL - if so then this issue can be moved to done.

**Comment by edwinmp** [comment]
@k8hughes yes, the documentation is fine
