### ISSUE TITLE
Boolean fields don't display on the front end

### ISSUE THREAD

**Issue by akmiller01** [devinit/ddw-analyst-ui#249]
I've imported the column "x_covid" from the "iati_transactions" table as a Boolean. You're able to filter the column on the front end by selecting "is equal" and putting the strings "TRUE" or "FALSE" and they appear when exporting the CSV, but the boolean values print as blank strings on the preview table:

![image](https://user-images.githubusercontent.com/2836840/88563071-81d43680-cfff-11ea-8860-f22dea705669.png)

Worth coding in a display for boolean fields @edwinmp ? Or do we want to work-around this for now and just made "x_covid" a string field?

**Comment by edwinmp** [comment]
Since the API returns proper booleans, this should be a proper FE fix ... should be simple.
