### ISSUE TITLE
Data source missing when viewing someone else's query

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#255]
Active data set not displaying. See pic.

![DDW Source detail](https://user-images.githubusercontent.com/3491562/88647987-75fb7980-d0be-11ea-9ffb-0378d371b9cd.png)

**Comment by akmiller01** [comment]
Are you still seeing this bug @bill-anderson ? Just tried viewing the website from your account, and other user's queries show up greyed-out (to indicate you're not allowed to edit them).

![image](https://user-images.githubusercontent.com/2836840/93598584-e0c48500-f98a-11ea-9f02-c415b057b5f3.png)

We could make you an admin if you want the ability to edit other people's queries.

**Comment by bill-anderson** [comment]
I can see the source now. I don't need access
