### ISSUE TITLE
Query preview slow?

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#259]
Previewing a query is a lot slower than before. Is this to be expected?

https://ddw.devinit.org/queries/data/598  :  1:45 min to load preview     1:25 to export csv
https://ddw.devinit.org/queries/data/602  :  1:30 min to load preview     1:30 to export csv

**Comment by edwinmp** [comment]
@bill-anderson this has been fixed ... please verify. The preview should now be significantly faster as it only loads 10 rows at a time.

**Comment by bill-anderson** [comment]
Yes, preview is now 'instant'. 

However all saves of queries, irrespective of complexity, now take a couple of minutes.

**Comment by edwinmp** [comment]
Thanks for raising this @bill-anderson ... the row counter is clearly synchronous ... will add that to my priority ToDo

NB: use celery to schedule row counting ... see [here](https://stackoverflow.com/a/11915280)

**Comment by edwinmp** [comment]
Done the basic optimisation on this ... if it's still slow, then further optimisation shall need be done on the DB. Think this is being handled in other issues.

**Comment by k8hughes** [comment]
@edwinmp can we close this issue now then?
