### ISSUE TITLE
Delete 2 unnecessary columns

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#263]
x_hum_appeal_vocabulary
x_hum_emergency_vocabulary

Both of these point to single vocabulary. x_hum_appeal_code will always be an OCHA plan code. x_hum_emergency code will always be a Glide number. cf #261

**Comment by akmiller01** [comment]
Hey @bill-anderson just working through these now. Issue #261 asked to delete
```
humanitarian_scope_code
humanitarian_scope_type
humanitarian_scope_vocabulary
```

But I think if we delete those and the x_ prefixes above, this information will be removed from the table entirely, correct?

**Comment by akmiller01** [comment]
Just realized my mistake. You're not asking for the x_codes to go away, just the vocabularies. You can disregard my comment above.

**Comment by akmiller01** [comment]
Done https://github.com/devinit/ddw-analyst-ui/pull/278
