### ISSUE TITLE
Add auto-deployment on updating core branches (develop & master)

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#265]
I'll do this one myself ... consider it my introduction to intermediate dev ops. Must be done with GitHub Actions.

**Comment by edwinmp** [comment]
Maria had worked on this for a bit, but not successfully so I had to revert it. I think this is a good opportunity for us to get more familiar with [dokku](http://dokku.viewdocs.io/dokku/)

**Comment by k8hughes** [comment]
Given the recent work that is happening as a result of the "5 whys" discussion that we had - should this issue remain open? @edwinmp

**Comment by edwinmp** [comment]
This is done and currently being managed in another issue... closing
