### ISSUE TITLE
Cancelling an export request

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#268]
I hit export csv and realised the filter was wrong and query would be massive. 

I hit <ESC> and it appeared to cancel. Is this correct?

Would be nice to have a message display during export - showing not only progress but also advice on how to cancel.

**Comment by edwinmp** [comment]
Once the export starts, it under the control of the browser's download feature ... all the actions including pausing & cancelling are then controlled by the browser. Depending on the browser you're using, this will appear differently and is beyond our scope.
On Chrome:
<img width="553" alt="Screenshot 2020-12-08 at 10 57 47" src="https://user-images.githubusercontent.com/5672438/101456707-81e92900-3945-11eb-83e9-4b252ac0246c.png">

<img width="364" alt="Screenshot 2020-12-08 at 10 58 05" src="https://user-images.githubusercontent.com/5672438/101456723-86addd00-3945-11eb-85ce-dca3eed6162e.png">
