### ISSUE TITLE
Order of columns when viewing data

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#270]
This seems to be random. Is there any control over this? Can we specify a column order (Not in the query but in the UI generally)?

![colorder](https://user-images.githubusercontent.com/3491562/88799550-90a51f80-d19e-11ea-934d-88939b0cdf14.png)

**Comment by edwinmp** [comment]
Nope ... the order is determined at the query builder stage ... perhaps this is something we can add down the road to compliment the one in issue #233 
Perhaps integrating with Google Sheets can provide all these features & more without too much dev work.

**Comment by k8hughes** [comment]
@edwinmp would it be worth considering this for the advanced query builder?

**Comment by edwinmp** [comment]
Absolutely ... shall be handled in issue #181

**Comment by edwinmp** [comment]
Will be added to the current QB under PR #498

**Comment by k8hughes** [comment]
@edwinmp there is a PR that you linked here - did it get released?  When it is on staging please tag @dean-breed

**Comment by dean-breed** [comment]
All done!
