### ISSUE TITLE
IATI Publishers table

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#276]
Please load 

[IATI Publishers.xlsx](https://github.com/devinit/ddw-analyst-ui/files/5001290/IATI.Publishers.xlsx)

**Comment by akmiller01** [comment]
Done https://github.com/devinit/ddw-analyst-ui/pull/278

**Comment by bill-anderson** [comment]
I can't see this in the list of data sources?

**Comment by akmiller01** [comment]
It's in code review before merging and deployment @bill-anderson, same as the other issues.

**Comment by k8hughes** [comment]
@akmiller01 has this issue been completed?  Do we still need it in code review?

**Comment by k8hughes** [comment]
@bill-anderson can you check this over and close it if it is fine?

**Comment by bill-anderson** [comment]
Checked. All good
