### ISSUE TITLE
Re-ordering steps in query builder

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#296]
The order in which steps are run is important for the performance of the query. 

- When an edit is saved the step is moved to the end of the query.
- It isn't possible to insert a step

This means that you need to rebuild a query from scratch every time you want to edit it.

**Comment by edwinmp** [comment]
This isn't probable ... each subsequent step is dependent on the previous steps... if you have 4 steps & edit the first one, it invalidates the other 3, so u'll need to change them all. There's no way around that. It's the same with inserting a step ... may as well get rid of all the other steps up until the point you wish to insert a new one.

At this point, I'd caution care when creating these queries - best to know what you want to do before diving in, cos as you can see, with this kind of high dependency, there's limited flexibility.

**Comment by bill-anderson** [comment]
I can understand that under certain circumstances inserting a step could cause a problem. The use case I am referring to is building complex filters - for which this shouldn't be a problem, right?

Could we not facilitate reordering together with error messaging when users do something illogical? Even if the error only says "you've done something stupid".

I want to push on this as I think complex queries (primarily involving joins and filters) will become more frequent. Analysts will build these through trial and error - so they won't know exactly what they want to do before diving in.

**Comment by edwinmp** [comment]
If it's enough to accompany it with errors & warnings, then we'll build it. I'll think on an intuitive design for it that fits well with what we already have. Now that the design is wider & more focused, it should be easier to add more functionality without crowding it.

**Comment by k8hughes** [comment]
@edwinmp can we link this into the advanced query builder work?

**Comment by edwinmp** [comment]
Sure, but it'd be nice to have in the current version as well.

**Comment by k8hughes** [comment]
@dean-breed  can you test this?  @davidebukali will ping you when it is on staging...

**Comment by dean-breed** [comment]
Sure - @davidebukali let me know when it is on staging!

**Comment by davidebukali** [comment]
Alright @dean-breed we are making a release, will reach out when it's deployed.

**Comment by davidebukali** [comment]
@dean-breed its now on [staging](https://staging-ddw.devinit.org)

**Comment by dean-breed** [comment]
Thanks @davidebukali - this seems to work well to me!

**Comment by davidebukali** [comment]
Great ... thanks @dean-breed
