### ISSUE TITLE
Intergrate theme

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#3]
Find, purchase and integrate a Material design theme.

**Comment by akmiller01** [comment]
Hey @edwinmp , is this purchased and not yet integrated? Or is this issue done?

**Comment by edwinmp** [comment]
Hadn't seen this issue. It's done ... will close it.

We went with the [Material Dashboard Pro](https://www.creative-tim.com/product/material-dashboard-pro) theme purchased from Creative Tim. It's a Bootstrap 4 theme so it's easy to integrate with [React Bootstrap](https://react-bootstrap.github.io/).
