### ISSUE TITLE
DAC reference file updates

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/ddw-analyst-ui#315]
The following DAC reference files have been updated:

[OECD CRS aid type reference file.xlsx](https://github.com/devinit/ddw-analyst-ui/files/5187222/OECD.CRS.aid.type.reference.file.xlsx)

[OECD DAC CRS donor type reference file.xlsx](https://github.com/devinit/ddw-analyst-ui/files/5187225/OECD.DAC.CRS.donor.type.reference.file.xlsx)

[OECD CRS sector mapping sector code to ITEP sector.xlsx](https://github.com/devinit/ddw-analyst-ui/files/5187224/OECD.CRS.sector.mapping.sector.code.to.ITEP.sector.xlsx)

New rows have been added with the latest info where applicable (for example, new donors) and new columns have been added to allow users to perform aggregations (for example transfer and non-transfer ODA in the aid type file and humanitarian and development ODA in the sector mapping file). Please let me know if there are any questions.

**Comment by akmiller01** [comment]
Uploaded here https://github.com/devinit/ddw-analyst-ui/pull/323

**Comment by akmiller01** [comment]
@Duncan-Knox I'm also seeing _X000d_ in a few places on the Aid Type reference file. Is that a special character that Libreoffice is failing to read?

![image](https://user-images.githubusercontent.com/2836840/92791880-0f36d480-f37b-11ea-9d29-13e2aebdc536.png)

**Comment by Duncan-Knox** [comment]
Hi @akmiller01 sorry for the delayed reply. X000d should not be in the file so there seems to be some kind of issue with the reading. It might link to an accidental empty row in the cell before the text starts. Would it help if I resend the file?

**Comment by akmiller01** [comment]
Hm yes, reupload file or just confirm if I delete those odd characters it will be file. Will need to make a new PR

**Comment by Duncan-Knox** [comment]
It's fine to delete those odd characters.

**Comment by akmiller01** [comment]
https://github.com/devinit/ddw-analyst-ui/pull/339
