### ISSUE TITLE
IATI fields to index

### ISSUE THREAD

**Issue by akmiller01** [devinit/ddw-analyst-ui#320]

**Comment by akmiller01** [comment]
Suggesting:

- iati_identifier
- title_narrative
- description_narrative
- transaction_description_narrative
- x_transaction_year
- x_yyyymm
- x_sector_code
- x_dac3_sector
- x_recipient
- x_recipient_code
- x_recipient_type
- x_country
- x_country_code
- reporting_org_type_code
- transaction_type_code

**Comment by bill-anderson** [comment]
Could you explain how free text columns are indexed? And do they take longer to index? 

I would skip free text columns and names that dupicate codes (country / recipient). And add defaul vocabulary and the new recipient and sector numbers. And add reporting_org_ref. 

I don't think it is a problem if a complex free text queries take 5 minutes.

**Comment by akmiller01** [comment]
Just working this out with Chris. All text columns were being indexed with GIN, which allows text searches within the free text. For any column we'd want to use boolean operators on (=, <, >) we should switch to a BTREE index.

**Comment by akmiller01** [comment]
Btree indexes implemented in the R script: https://github.com/devinit/ddw-analyst-ui/pull/340/commits/f2bf834dba4f21c98656effa45bcbd154ffc7635

**Comment by akmiller01** [comment]
Pasting PR so this issue gets properly linked: https://github.com/devinit/ddw-analyst-ui/pull/340

**Comment by wakibi** [comment]
@akmiller01 @bill-anderson shouldn't this be closed? The PR got merged already.

**Comment by akmiller01** [comment]
PR is merged, but indexing needs to be run, and analyst tested.

**Comment by bill-anderson** [comment]
This question is late (sorry, I forgot ...)
If the query is run in steps and steps one and two both involve filters on indexed columns, will step two use the index? I know that the indexing engine should resolve multiple indexes in a single query, but does it handle multiple steps??

**Comment by wakibi** [comment]
@bill-anderson that would largely depend on how big the result from step one is. If too huge, chances are the index will be used in two as well. Else it will be ignored if no performance gains are noticed by the DB engine.

**Comment by k8hughes** [comment]
@akmiller01  doing a git clean up today and this was in the backlog but it looks like it actually might be done?  Can you make sure to move issues on the kanban when you work on them?  Does this need a review or can we close it?

**Comment by akmiller01** [comment]
I still need to run the indexing and it needs to be checked. But columns are in flux a little bit now; I have some work to do around countries/regions for Bill's use cases and then I can reindex.

**Comment by k8hughes** [comment]
@akmiller01 just giving this another nudge - it is under function review, who should we asign this to?

**Comment by akmiller01** [comment]
Hi @k8hughes , this feature has been completed a couple of times over now, but each time a new column or method is requested it changes how the indexing works. Right now I'm waiting to see how this feature impacts the indexing: https://github.com/devinit/ddw-analyst-ui/pull/359

I could just run the indexing as-is right now, so we can test the effect on query speed, before new columns are implemented?
