### ISSUE TITLE
IATI Transactions: Rethinking default vocabulary

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#322]
Now that we have recipient_number and sector_number, and analysts will need to become familiar with using these, is it worth considering reconfiguring default vocabulary to be vocabulary_number where vocabulary_number = 1 follows the current default-vocabulary logic.

This would make these slightly difficult concepts for the uninitiated  more consistent and easier to remember/use?

**Comment by k8hughes** [comment]
@akmiller01  does this make sense to you?  Would you be able to pick this one up?

**Comment by akmiller01** [comment]
I think that makes sense. So if we had 5 sectors with vocabularies 1, 1, 2, 99, 99, the vocabulary_numbers would be 1, 1, 2, 3, 3?

**Comment by bill-anderson** [comment]
So long as current default vocab logic points to 1, yes.

So if we had 5 sectors with vocabularies 2, 99, 99, 1,1 the vocabulary_numbers would be  2, 3, 3,1,1

**Comment by akmiller01** [comment]
Refactor here: https://github.com/devinit/ddw-analyst-ui/pull/340/commits/89459a61f9eb9b0116a0ac43e3819f1cd45feacf

So default priority order is 1 if it exists, followed by 2 if it exists, followed by the most common vocabulary in the activity, followed by all of the other vocabularies in the activity ordered alphabetically.

**Comment by akmiller01** [comment]
Pasting PR so this issue gets properly linked: https://github.com/devinit/ddw-analyst-ui/pull/340

**Comment by k8hughes** [comment]
@akmiller01 does this still belong in the backlog?  or is it in progress?

**Comment by akmiller01** [comment]
This one is done and reviewed.
