### ISSUE TITLE
Add collaboration-type to IATI transactions

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#328]
Flow Type >> Collaboration Type >> Finance Type >> Aid Type are interconnected DAC classifactions. We missed out collaboration type.

**Comment by k8hughes** [comment]
@bill-anderson is this one for @akmiller01 or one for @wakibi ?

**Comment by bill-anderson** [comment]
Would be good for @wakibi to do this with support from @akmiller01

**Comment by k8hughes** [comment]
@akmiller01 can you review this one for us.  There is a PR for it:  https://github.com/devinit/ddw-analyst-ui/pull/373

**Comment by akmiller01** [comment]
Small change needed for the code to function, left instructions in the PR review.

**Comment by k8hughes** [comment]
This has been deployed
