### ISSUE TITLE
BTREE indexing for top filtered filtered fields

### ISSUE THREAD

**Issue by wakibi** [devinit/ddw-analyst-ui#329]
We need to pick the top filtered fields, and apply BTREE indexing on them then monitor how that will impact performance. We also need to make sure we add this info to the user manual.

**Comment by akmiller01** [comment]
Applied IATI Btree in this PR, but we will probably want to add/document more: https://github.com/devinit/ddw-analyst-ui/pull/340

**Comment by k8hughes** [comment]
@akmiller01  and @wakibi it seems there was a PR deployed but the issue is still open - do we still need it?  If what is required is documentation can we agree who is going to take that forward and action it so this is completed?

**Comment by akmiller01** [comment]
I believe @wakibi ran `indexing.sh` after this was deployed, so we should be fine. But I'll wait for his confirmation.

**Comment by wakibi** [comment]
This was done. Closing.
