### ISSUE TITLE
Master / Slave Architecture set up and backup

### ISSUE THREAD

**Issue by wakibi** [devinit/ddw-analyst-ui#334]
Confirm the requirements to set up master-slave for the DDW. This should also look at the back up options we have

**Comment by k8hughes** [comment]
@wakibi I think we still need this issue right?

**Comment by wakibi** [comment]
Yes, @k8hughes we do need this. It's one of those that will need proper planning. Docker adds an extra layer of complexity, but the recent deployment pipeline I worked on factored this in. We'll just build on that.

**Comment by wakibi** [comment]
We'll need 3 days to set this up and test it thoroughly.

**Comment by k8hughes** [comment]
Moving this to blocked as Chris will do this after his Easter leave.  Will require extra storage for testing.
