### ISSUE TITLE
ETL: Populate default vocabulary when sector code is missing

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#338]
This query - https://ddw.devinit.org/queries/data/725 - fails to find WHO activities

The reason is the incorrect coding of sectors as narrative, not code.

```
<sector vocabulary="1" code="">
  <narrative xml:lang="en">72011</narrative>
</sector>
```
ETL does not record sector vocabulary or default vocabulary. 
It should.

```
IF sector-code is missing
   IF sector vocabulary is present use it
   ELSE sector vocabulary = 99
```

**Comment by akmiller01** [comment]
Here's my implementation: https://github.com/devinit/ddw-analyst-ui/pull/340/commits/7ffc0678b81217ff3f9f1e5f8fcea7f1fb2297b9

So before vocab was defaulting to blank if missing. And sectors were excluded entirely if "code" was blank. Now it will count all sectors, defaulting to vocab "99" and percentage "100" even if code is blank.

**Comment by akmiller01** [comment]
I guess while we're doing this, it's worth discussing whether defaulting "percentage" to "100" when missing is appropriate @bill-anderson. It could lead to some odd double counting, but not defaulting to "100" would also lead to the transaction being unsplitable when the publisher has neglected to include a percentage.

**Comment by akmiller01** [comment]
Pasting PR so this issue gets properly linked: https://github.com/devinit/ddw-analyst-ui/pull/340

**Comment by k8hughes** [comment]
@akmiller01 as this has a deployed PR connected to the issue should it be closed?

**Comment by akmiller01** [comment]
> @akmiller01 as this has a deployed PR connected to the issue should it be closed?

yes.
