### ISSUE TITLE
Constant prices

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#342]
We need to convert all value columns to be deflated with a base year of the most recent year available from the DAC (currently 2019)

**Comment by dean-breed** [comment]
To clarify, this would be for the newly created IATI transaction spec only

**Comment by k8hughes** [comment]
@dean-breed  - what are your current thoughts on this and whether it is still required?  if so what would you be expecting?

**Comment by k8hughes** [comment]
@dean-breed are you happy for this issue to be close or do you think we still need it?

**Comment by dean-breed** [comment]
@k8hughes I think this should remain open to be used in the discussions. This should be done and we could automate it. I will add this to the spreadsheet of discussion points we are creating
