### ISSUE TITLE
Error viewing dataset

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#343]
https://ddw.devinit.org/queries/data/737

![uibug](https://user-images.githubusercontent.com/3491562/94247633-4da0c780-ff15-11ea-9da5-39d18a258af0.png)

**Comment by edwinmp** [comment]
@bill-anderson step 4 (Default Vocab) of this dataset is referencing a column that doesn't exist ..

**Comment by bill-anderson** [comment]
So how was I able to select it??

**Comment by edwinmp** [comment]
I'm sure it was valid the first time this dataset was created, but something has changed since then ... either the data source was changed, or the column was removed from the data source or renamed.

**Comment by wakibi** [comment]
@bill-anderson @edwinmp the column name changed to `x_vocabulary_number` as of yesterday. See this commit [89459a6](https://github.com/devinit/ddw-analyst-ui/pull/340/commits/89459a61f9eb9b0116a0ac43e3819f1cd45feacf) and this [PR](https://github.com/devinit/ddw-analyst-ui/pull/340)

**Comment by edwinmp** [comment]
@akmiller01 for such changes, you'll probably need to add a data migration that updates all affected datasets

**Comment by wakibi** [comment]
@akmiller01 we can have a discussion on how best to handle these going forward.

**Comment by akmiller01** [comment]
It wasn't a selectable column as soon as these changes were implemented. So this should have only affected existing queries, not new ones.

As for migrations, it's worth asking how often we're going to be adding/deleting columns from the data.

**Comment by edwinmp** [comment]
@akmiller01 yes the concern lies with existing queries as this is a breaking change for them ... with no alert triggered by such a change, a lot could be silently breaking ... within a data migration, it should be relatively easy to filter datasets based on data source, find steps with `query_kwargs` that have the old column name and update it to the new one. Then update the aliases as well. It should be a prerequisite for merging this kind of PR @wakibi . You could avoid it by first manually checking for usages on the live DDW.

Curious, is it natural for IATI tables to undergo this kind of change often?

**Comment by akmiller01** [comment]
The IATI table is still in it's infancy, so changes to the methodology are being requested. It will settle down eventually.

**Comment by k8hughes** [comment]
We still need to have a better way of tracking changes, making sure the whole team is aware and informing our users, especially if we might break the queries that have been set up already.  Can you agree the right dev processes so that this doesn't happen again?
