### ISSUE TITLE
IMF WEO October 2020

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/ddw-analyst-ui#354]
The New IMF WEO for October 2020 has been released today. Could we look at including this update on the DDW please?

**Comment by akmiller01** [comment]
Code for review here: https://github.com/devinit/ddw-analyst-ui/pull/355

Only major change seems to be the IMF has coded this year as UTF-16 instead of UTF-8.

**Comment by akmiller01** [comment]
Data is updated on the DDW @Duncan-Knox !
