### ISSUE TITLE
IATI publishers table

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#365]
We need to include a table of IATI publishers with the following fields:
Reporting organisation narrative
Reporting organisation reference
Full name
Country
Commitments
Disbursements

We may also need to consider any flags needed (i.e. year end).

**Comment by k8hughes** [comment]
@akmiller01 can you look at this and whitelist the IATI publishers table so it can be editted via the FTS update feature?

**Comment by akmiller01** [comment]
https://github.com/devinit/ddw-analyst-ui/pull/367 Done in this PR.

**Comment by akmiller01** [comment]
You might want to take a look at the current state of the publisher sheet @dean-breed . Here's what it looked like when it was first uploaded: https://github.com/devinit/ddw-analyst-ui/blob/develop/data_updates/manual/CSV/iati_publishers.csv

Do we need to remap some of those columns?

**Comment by dean-breed** [comment]
Yes @akmiller01 - we used something slightly different for the most recent analysis. How do I edit this table via the FTS update feature?

**Comment by akmiller01** [comment]
@dean-breed if you download a copy of the above, make your edits, and send it back to me, I can include it in the pull request to whitelist it.

**Comment by dean-breed** [comment]
Does it matter if I change the format of it a bit?

**Comment by dean-breed** [comment]
@akmiller01 - forgot to tag you above

**Comment by akmiller01** [comment]
Not at all, you can change it however we need it.

**Comment by bill-anderson** [comment]
Can I revise @dean-breed's list of fields:

Reporting Organisation Reference
Reporting Organisation Name
Organisation Name (DI)
IATI Registry Id
DAC Donor Code
DAC Agency Code
FTS Organisation Id
Organisation Type (IATI)
Organisation Type (DI)
Commitment Usability
Spend Usability
HQ Country

Content of Usability columns need further defining
Dean can you review and confirm ^^

**Comment by dean-breed** [comment]
This is top of my priority list after the TASC work. I should be able to review it Tuesday but I appreciate that is some time away

**Comment by dean-breed** [comment]
Apologies for the delay on this @akmiller01. This just contains the donors we used for the briefing with scores of 0 (don't use), 1 (review comment before using), 2 (go ahead).

On a side note, how bizzare that GH doesn't support CSVs in issues...

[iati_publishers.txt](https://github.com/devinit/ddw-analyst-ui/files/5710857/iati_publishers.txt)

**Comment by akmiller01** [comment]
> On a side note, how bizzare that GH doesn't support CSVs in issues...

It supports zips, so I tend to just compress them!

**Comment by akmiller01** [comment]
Replaced the old table here: https://github.com/devinit/ddw-analyst-ui/pull/384

**Comment by dean-breed** [comment]
[iati_publishers.zip](https://github.com/devinit/ddw-analyst-ui/files/5715374/iati_publishers.zip)

Sorry @akmiller01 - one small change

**Comment by akmiller01** [comment]
Cheers @dean-breed , updated the PR.

**Comment by k8hughes** [comment]
@akmiller01 @dean-breed  can this issue now be closed?

**Comment by akmiller01** [comment]
Yes, I believe this is complete.
