### ISSUE TITLE
Update IATI Publishers Table during ETL

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#366]
(based on our discussion yesterday)

During ETL

1. Check whether reporting-org_ref exists in the IATI Publishers Table
2. If not append it and reporting-org_narrative to table

**Comment by k8hughes** [comment]
@bill-anderson @akmiller01  @wakibi Is this something we should still be aiming to do?  If so can someone map out the steps requirea and put a time estimate on the issue?

**Comment by akmiller01** [comment]
Not too difficult a task, but I don't know if it's still needed. Maybe 2 days of dev time at the very most:

- [ ] Create a new script that takes DISTINCT values of iati_transactions table and compares them to iati_publishers table
- [ ] For all new publishers that are in iati_transactions but not in iati_publishers, create a new row with that publisher's ref
- [ ] Set up this new script to run after iati_transactions is refreshed

**Comment by wakibi** [comment]
@bill-anderson there is `reporting-org_narrative` column in the publishers table. Is it synonymous with `country_or_org_name`?

**Comment by dean-breed** [comment]
@wakibi Those columns are not synonymous. Reporting Org Narrative is the name IATI uses for an organisation whereas Country or Org Name is the name we colloquially use for the donor. This also means many Reporting Org Narratives will come under the same Country or Org Name. For example, many organisations (FCDO, DHSC, BEIS) will all come under 'United Kingdom'.

**Comment by wakibi** [comment]
@dean-breed does that mean, currently we are not capturing the `reporting-org_narrative` and we need to add it?

**Comment by dean-breed** [comment]
@wakibi I don't see any harm in adding it. I think this issue was opened to make sure we added a new row in the publishers table every time a new organisation joined IATI. Therefore, reporting org ref is sufficient but it would, perhaps, be clearer for users if we also use narrative.

**Comment by wakibi** [comment]
Thanks, @dean-breed. Cheers

**Comment by wakibi** [comment]
@bill-anderson this has been deployed today.

First run will be over the weekend when the new IATI data is downloaded.
