### ISSUE TITLE
ITEP sectors need updating

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#374]
We need to update the ITEP <- DAC sector mapping

**Comment by edwinmp** [comment]
@akmiller01 this one sounds like one of yours

**Comment by dean-breed** [comment]
There is not a major rush on this @akmiller01- we can come to it when we have time. I just wanted to open it

**Comment by k8hughes** [comment]
@akmiller01 is this something we can now take forward?

**Comment by akmiller01** [comment]
Looks like the mapping hasn't been updated since Sept 2020: https://github.com/devinit/ddw-analyst-ui/blob/develop/data_updates/manual/CSV/oecd_crs_sector_itep_map.csv

If @dean-breed has a new mapping we can replace it.

**Comment by k8hughes** [comment]
@dean-breed do we want to keep this issue open?

**Comment by dean-breed** [comment]
@k8hughes Yes

**Comment by dean-breed** [comment]
This is now stored here: https://github.com/devinit/ddw-data-update-configs/blob/master/manual/CSV/oecd_crs_sector_itep_map.csv

It is done but will also, ideally, need the table to be updated as part of the cycle. Similar to how we want to update the publishers table.

**Comment by k8hughes** [comment]
So do we need to have some sort of script to automate the updates?

**Comment by dean-breed** [comment]
@k8hughes I think so! It could be in the same feedback loop as the publishers table as it just checks the table for unique entries of a different field

**Comment by wakibi** [comment]
@dean-breed where does this data come from? Looking for guidance on how to implement the auto-update script for this as it's been done manually previously

**Comment by dean-breed** [comment]
I'm not sure at the moment and don't consider this to be high priority. We should still keep this open for when time allows
