### ISSUE TITLE
Make spotlights data available on the DDW UI

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#376]
This is what @wakibi wrote on slack:
The data is on the same server as the DDW, but to be able to put that data on the DDW under the current set up, we shall need to do the following;
1. Expose the DDW DB port so the Spotlights API can access it or Set up the spotlights API to run from  a docker container on the same server as the DDW
2. Spotlights data uses 5 schemas (3 active, 2 redundant), we shall need to factor that in, and add them under the sources table in the DDW.
3. Cross check and make sure no table names clash.
One above is the most tricky one as I have never done port forwarding to a docker container before.

@akmiller01 have you ever done port forwarding to a docker container?

**Comment by wakibi** [comment]
On second thought, it should be fairly easy, we simply map the docker container's port to the corresponding host's port, much the same way we do for the docker containers hosting the web servers. So should not be a problem.
