### ISSUE TITLE
Data source displaying on Published datasets is inconsistent

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#383]
In attached pic the source on a number of them doesn't match the query
eg. Final ODA data is not IATI
eg. IATI ODA Publishers check is not from FTS
This is a display issue - query iteself is ok
![ddw2](https://user-images.githubusercontent.com/3491562/102483650-f49c8780-405c-11eb-86a0-6d054c6c5924.png)

**Comment by k8hughes** [comment]
@davidebukali @wakibi any idea what the cause of this might be?

**Comment by davidebukali** [comment]
@k8hughes I looked at the api sources results, they appear accurate for each published dataset; Final ODA data is OECD Creditor Reporting System and  IATI ODA Publishers check is IATI; as Bill mentioned, its most likely a display issue on the frontend when matching sources to their respective datasets.

**Comment by k8hughes** [comment]
@bill-anderson is this bug still present?
