### ISSUE TITLE
Aggregate

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#39]
Select columns, select aggregation function, select column

**Comment by Duncan-Knox** [comment]
Under the operation steps the 'Of' box does not return any columns to select or allow anything to be typed and entered to select a column. It states 'no results found'. Is this a bug?

**Comment by edwinmp** [comment]
@akmiller01, are you adding the `data_type` field to the columns? Won't be able to show any columns in the drop-down without it.

**Comment by akmiller01** [comment]
Yep. It's already in my `models.py` `SourceColumnMap` object. Once I get Duncan's last piece of data in, we can merge data-collection-folder to develop?

**Comment by edwinmp** [comment]
They all currently seem to have a `data_type` of `null`, so if the merge can fix that, then definitely merge.

**Comment by edwinmp** [comment]
Hi @Duncan-Knox, the column issue should be fixed now ... please note that for arithmetic operations, only columns with numerical data shall be returned.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp thank you for the update. I look forward to testing the aggregation and transform functions.

**Comment by edwinmp** [comment]
Hi @Duncan-Knox ... have you encountered any more issues with the aggregate or transform? If not, I'd like to close this.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp , Let me cover the full range of functions now. I've not tested all within aggregate.

**Comment by Duncan-Knox** [comment]
I have not encountered any further bugs testing the aggregate function (beyond that raised on distinct). 

A thought on standard deviation. I'm tempted to say we note that the standard deviation operation refers to a sample standard deviation as opposed to population so users are clear, ie title 'standard deviation (sample)'. This said, for most of the data within the UI at the moment, I'd expect to apply a population SD (complete data at the country level). Also bear in-mind, in my experience I'd guess SD would be a relatively low use function (occasional internal work). How does this square with your experience @akmiller01?

**Comment by akmiller01** [comment]
@Duncan-Knox true. Maybe the likes of Zach and Dan W would use STDDEV more frequently.

**Comment by k8hughes** [comment]
@Duncan-Knox can this be closed or is more work required?

**Comment by Duncan-Knox** [comment]
Done @akmiller01 and @k8hughes. Checked with Dan.W and he uses STDDEV for occasional internal work. Both sample and population. Feel free to add 'sample' in the title in the case you think it may be useful to make that clear to users or is necessary.

**Comment by Duncan-Knox** [comment]
Happy to close this issue from my checks. Unless anyone has a reason to keep open.
