### ISSUE TITLE
Create IATI-DAC mapping tables

### ISSUE THREAD

**Issue by akmiller01** [devinit/ddw-analyst-ui#390]
https://docs.google.com/spreadsheets/d/1KNkCGemdQX4y8RkqXhVghO9keBLZQmjcFDRzOmJFIWs/edit

**Comment by k8hughes** [comment]
@akmiller01 what is the status of this?

**Comment by akmiller01** [comment]
I had created this issue so we wouldn't forget about the mapping files @bill-anderson made for the DAC update, but I don't know if they were ever actually used. If they're still useful I can create new tables out of each tab.

**Comment by k8hughes** [comment]
@bill-anderson I am assuming we need to keep this issue open till we have had the bigger IATI data discussion next week?
