### ISSUE TITLE
Move dataset copy feature away from the edit view to the list view

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#391]
Current location only allows making copies of the user's own datasets
![image](https://user-images.githubusercontent.com/5672438/104199438-7f905800-5438-11eb-8331-aa95a9f1dc39.png)

Move it here:
![image](https://user-images.githubusercontent.com/5672438/104199638-b9f9f500-5438-11eb-8cc7-c51ad5e09817.png)

**Comment by edwinmp** [comment]
@dean-breed you'll be glad to know we finally have this feature in a convenient location, allowing the duplication of any queries, published or not.
![image](https://user-images.githubusercontent.com/5672438/111677197-09d9ab80-8830-11eb-8a60-bad7d26a2a56.png)

**Comment by dean-breed** [comment]
That's brilliant @edwinmp! Thanks

**Comment by k8hughes** [comment]
Is there anything that needs to be updated in the user guidence as a result?  https://docs.google.com/document/d/1j10m46dLY-zb5Mee4JWncTGeOsf2o8oChSN90ZUu8vk/edit

**Comment by edwinmp** [comment]
That was already done as part of the issue's deliverables.

**Comment by k8hughes** [comment]
Brilliant!
