### ISSUE TITLE
Closing the old Linode server account

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#394]
Below is the email thread disscussing what is still active on this server.
Please can we make sure that we move what needs moving and close this account by the end of the month?

I'm tagging @akmiller01 @wakibi  and @edwinmp on this issue.  Can we distill this email thread into the clear action point we have to get the task done please?

@wakibi : No, the data is coming off the current Analyst UI server; all spotlights data at least. It’s just the API code that needs to be hosted elsewhere.
 

From: Alex Miller

Hi Chris,

Thanks for taking a look. Since https://api.devinit.org is still running, I presume it's still feeding from linode1009616_ddw? So presumably we need to re-host the API code on a different server, and then reconfigure the API code to point to the Analyst UI server instead of the old DDW before we can shut down the rest of the services.

Best,
-Alex
 
Alex Miller I Data Scientist

 
From: Chris Wakibi
 
Alex,
 
https://api.devinit.org is still running the spotlights API as you mentioned. We need to move it somewhere else if we are to shut down this server. Have looped in @Edwin Magezi as he does the FE for the Spotlights and it could be affected by any migrations (assuming some URLs are hard-coded IP addresses)
 
Also, all DDW data that was on (linode1009616_ddw) was moved to the Analyst UI server. I do not see anything else running off that server.
 
Christopher Wakibi | Senior Fullstack Developer

From: Alex Miller

Hi all,

Here's what remains running on the server:

I believe the Spotlight data was transferred off of the original DDW (linode1009616_ddw), but I don't know if any of the other data was archived. If we can dump the contents of the database and store it somewhere secure, that would be easy to shutdown and accounts for $82/month.

linode3186698_juds is running http://joinedupdata.org/en/about/ and costs $20/month.

linode3673430_dh_staging is still running https://api.devinit.org/ and I thought this had been migrated somewhere else as well but maybe I misunderstood. Do the spotlights still depend on this API, Chris? Or can we shut this one down?($20/month)

linode_ddw_dev is running a native postgres on port 65432 and a  dockerized postgres remapped to 5433, but otherwise I cannot find any services running on it or think of anything dependent on it. ($40/month)

If the Spotlights are de-coupled from api.devinit.org, I should be good to go ahead and shut down linode1009616_ddw (dumping the database to Box for preservation, maybe), linode3673430_dh_staging, and linode_ddw_dev.
Alex Miller I Data Scientist

Sign up to our newsletter and topic updates

**Comment by akmiller01** [comment]
I've concluded that all of the data from the old DDW has indeed been migrated over to the new database, and all of Donata's ETL scripts are archived in a private repository here: https://github.com/devinit/ddh_donata_scripts Therefore, I think we're fine to shut down linode1009616_ddw (213.168.251.124) and linode_ddw_dev (139.162.241.167).

**Comment by akmiller01** [comment]
linode1009616_ddw (213.168.251.124) and linode_ddw_dev (139.162.241.167) have been deleted. Chris is now working to re-deploy the DDW External API to another VM, at which point we can shut down linode3673430_dh_staging, at which point the account will just be linode3186698_juds.

I know @bill-anderson is still using http://joinedupdata.org/en/about/, so maybe once the Linode account is just linode3186698_juds we can change the billing information?

**Comment by k8hughes** [comment]
Yes that sounds fine, we'd need to agree what budget pays for JUDS and then let Nick W know so he can sort this out in FP.  @bill-anderson any ideas where we can charge JUDS to?

**Comment by bill-anderson** [comment]
I'm going to pass the buck to Claudia on this one.

**Comment by k8hughes** [comment]
@wakibi to update this issue with the details of spotlights API movement.

**Comment by akmiller01** [comment]
As of this morning, the only remaining Linode running on that account is JUDS.

**Comment by k8hughes** [comment]
Brilliant.   Bill and I agreed with Claudia that for the next year at least we will leave JUDS where it is and it will come from Richard's IT budget
