### ISSUE TITLE
Create new IATI transaction columns from participating_orgs

### ISSUE THREAD

**Issue by akmiller01** [devinit/ddw-analyst-ui#395]
```
I would name the columns as per the code list - i.e. Funding Organisations; Accountable Organisations; Extending Organisations; Implementing Organisations. (NB some publishers use org-ids but too few to standardise on ids)

I would populate these with Participating Organisation Narrative

I would delimit multiple values with ; rather than |
```

**Comment by k8hughes** [comment]
@akmiller01 as this is linked to a released PR should we be closing the issue?

**Comment by akmiller01** [comment]
PR is still open, awaiting discussion on `;` vs `|` as a separator: https://github.com/devinit/ddw-analyst-ui/pull/396

**Comment by k8hughes** [comment]
@akmiller01 @wakibi @dean-breed I think we still need this open right?

**Comment by dean-breed** [comment]
I think so - this will likely be part of the work we're discussing soon!

**Comment by dean-breed** [comment]
@k8hughes This has actually already been implemented apart from replacing | with ; so can be closed in my opinion.
