### ISSUE TITLE
Show feedback on making breaking changes to a query builder step

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#399]
e.g. With 2 steps, one a selected & the next one a filter, if the select step is edited to remove the column being filtered in step 2, a warning should at least be shown about this.

**Comment by k8hughes** [comment]
Has this been deployed?  if so we can move this to done

**Comment by edwinmp** [comment]
It's on staging, going to be part of the v2.9.0 update.

**Comment by k8hughes** [comment]
Ah ok.
@dean-breed it would be great if you could view this on staging and let us know if it is working as you'd expect.

**Comment by dean-breed** [comment]
This appears to work well. No obvious problems

**Comment by dean-breed** [comment]
@edwinmp @k8hughes this is all good to deploy.
