### ISSUE TITLE
Local login

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#4]
Add login fields, buttons, validation, response handling, navigation.

**Comment by edwinmp** [comment]
The basic UI development is done. Sure there's still some branding issues to clean up. Still need to get the validation & response handling completed, but have decided to finish the backend dependencies first.

![image](https://user-images.githubusercontent.com/5672438/53018229-e2526200-3462-11e9-898a-4bdbaeb47b7a.png)

**Comment by k8hughes** [comment]
It is looking nice 👍 
Do we need to use the brand colours?

**Comment by edwinmp** [comment]
It's one of the requirements for the UI, so I guess we have to. Though it can wait for now.
