### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#40]
Fetch resulting data from actions, show in table

**Comment by edwinmp** [comment]
@Duncan-Knox @akmiller01 I'm reopening this issue to handle any bugs that are specific to data loading, most of which are currently being logged on issue #41, which should only be for data export related issues.

**Comment by Duncan-Knox** [comment]
Hi, I am receiving quite strange behaviour with this one. http://138.68.138.212/queries/data/153/
Currently it is not loading. It was working before. One change I made was to alter the step called 'aggregate', changing the sum of 'usd Disbursement deflated' to 'usd Disbursement'. Since this change it has stopped loading the data. When I change the of criteria back to 'usd disbursement deflated' it continues to not load any data. Any help spotting if there is a bug behind this is most appreciated.

**Comment by akmiller01** [comment]
This is actually a problem with column names following an aggregate. If you don't group by Year, you won't have year to work with later:

```
analyst_ui=# SELECT "sq1"."year","sq1"."donor_code","sq1"."donor_name","sq1"."agency_code","sq1"."usd_commitment","sq1"."usd_disbursement","sq1"."aid_type","sq1"."finance_type","sq1"."usd_commitment_deflated","sq1"."usd_disbursement_deflated","sq1"."short_description","sq1"."purpose_code","sq1"."purpose_name","sq1"."sector_code","sq1"."project_title","sq1"."sector_name","sq1"."channel_code","sq1"."channel_name","sq1"."channel_reported_name","sq1"."recipient_name","sq1"."recipient_code" FROM (SELECT "sq0".* FROM (SELECT "sq0"."recipient_name",SUM("sq0"."usd_disbursement") "usd_disbursement_Sum" FROM (SELECT * FROM "repo"."crs_current" WHERE "flow_name"='ODA Grants' OR "flow_name"='ODA Loans' OR "flow_name"='Equity Investment') "sq0" GROUP BY "sq0"."recipient_name") "sq0" WHERE "sq0"."year"='2016') "sq1";
ERROR:  column sq0.year does not exist
LINE 1: ...sq0" GROUP BY "sq0"."recipient_name") "sq0" WHERE "sq0"."yea...
                                                             ^
```

**Comment by Duncan-Knox** [comment]
This one still isn't generating output. http://138.68.138.212/queries/data/154/. I've removed the filter and grouped aggregation sum by year and recipient id.

**Comment by akmiller01** [comment]
You're selecting "USD Disbursement Deflated" in the first step, and aggregating by "USD Disbursement" in the second:

```
analyst_ui=# SELECT "sq0"."recipient_code","sq0"."year",SUM("sq0"."usd_disbursement") "usd_disbursement_Sum" FROM (SELECT "year","recipient_code","usd_disbursement_deflated" FROM "repo"."crs_current") "sq0" GROUP BY "sq0"."recipient_code","sq0"."year";
ERROR:  column sq0.usd_disbursement does not exist
LINE 1: SELECT "sq0"."recipient_code","sq0"."year",SUM("sq0"."usd_di...
```

The select step isn't actually necessary

**Comment by Duncan-Knox** [comment]
Yep sorry. Just realised.

**Comment by Duncan-Knox** [comment]
Ah, adding selections when they have been filtered out with the aggregation returns no data too.

**Comment by akmiller01** [comment]
Should we maybe look at a way of passing these error codes to the user @edwinmp ? It might be useful to diagnose when no data appears.

**Comment by edwinmp** [comment]
This was handled in #101

**Comment by Duncan-Knox** [comment]
Happy to close this issue from my checks. Unless anyone has a reason to keep open.
