### ISSUE TITLE
Add policy marker columns to the IATI transaction split

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#402]
I believe these are at an activity level so it shouldn't be too heavy a lift. Let me know if anything is an issue @akmiller01

**Comment by akmiller01** [comment]
https://github.com/devinit/ddw-analyst-ui/pull/403

**Comment by k8hughes** [comment]
@akmiller01  don't forget to close issues / mark as done after the PR is deployed.
