### ISSUE TITLE
Error proof the DDW API endpoints

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#405]
Handle all potential errors, returning useful messages. For 500 errors, return proper messages but send an email to the registered admins with details on the error.

**Comment by edwinmp** [comment]
This was targeted towards the external API and is not a priority at the moment since direct value goes to the Spotlights.

**Comment by edwinmp** [comment]
Looking into our core DDW API endpoints & checking off those that don't need extra work

- [x] Login
- [x] Logout
- [x] Get Users
- [x] Get User
- [x] Get Scheduled Events
- [x] Create Scheduled Event
- [x] Get Scheduled Event Run Instances
- [x] Get Scheduled Event Run Instance
- [x] Get Sources
- [x] Get Source
- [x] Get Source Datasets
- [x] Get Source History
- [x] Get User Source Datasets
- [x] Export Dataset Data
- [x] Change Password
- [x] List Update Scripts
- [x] Execute Update
- [x] Update Table
- [x] Download Table
- [ ] Download Table By Schema
- [ ] Get Datasets
- [ ] Get User Datasets
- [ ] Get Dataset
- [x] Get Dataset History
- [x] Get Dataset Data
- [x] Get Dataset Alias
- [x] Get Dataset QueryTime Estimate
- [x] Get Saved Query Sets
- [x] Get Saved Query Set
- [x] Get All Frozen Datasets
- [x] Get Frozen Dataset

**Comment by edwinmp** [comment]
NB: https://realpython.com/lessons/capturing-stack-traces/

**Comment by edwinmp** [comment]
@ThatcherK refer to the checklist above for endpoints that require some extra error handling. Most of them don't even have a `try/except` wrapper around their code and those that do are only taking care of a few specific errors. The goal is to make sure that any error that can occur is handled gracefully. This will need a general `except` that'll catch any errors, a nice error message for such situations, and an alert email sent to registered administrators with details of the error (refer to [this](https://github.com/devinit/ddw-analyst-ui/issues/405#issuecomment-799465680) comment for a potential logging solution)

**Comment by ThatcherK** [comment]
So this is no longer pointing to the external API

**Comment by edwinmp** [comment]
> So this is no longer pointing to the external API

In case this was a question, nope, it's not.
