### ISSUE TITLE
Upgrading our version of Postgres from 11 to 13.1

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#420]
We are a few versions behind on the version of Postgres that we are using.  Upgrading it might be a bit of a big job, and might require downtime so I think we should plan it carefully before we do any work.

@wakibi  and @akmiller01  can you discuss on this issue options for how we can do this with minimal downtime?  Then we can work out with the R&A team a time for scheduling the work where they can allow for the downtime.

**Comment by akmiller01** [comment]
I think we should be able to do this with minimal downtime; biggest impact will be slow performance while the processing happens.

Easiest process in my mind would be something like:

- [ ] `pg_dumpall` current database
- [ ] Create new docker volume (current one is `metadata` so maybe `metadata2`)
- [ ] Spin up Postgres 13.1 container mounted to `metadata2` (maybe `db2`)
- [ ] `pg_restore` dump into `metadata2`
- [ ] Edit `docker-compose.yml` and `Dockerfile_pg` so that original `db` is built as 13.1 and mounted to `metadata2`
- [ ] Bring down `db2`, bring down `db`, rebuild and relaunch `db`

**Comment by k8hughes** [comment]
@wakibi can you add notes from our discussion today on here?  You found a simple solution

**Comment by wakibi** [comment]
> I think we should be able to do this with minimal downtime; biggest impact will be slow performance while the processing happens.
> 
> Easiest process in my mind would be something like:
> 
> * [ ]  `pg_dumpall` current database
> * [ ]  Create new docker volume (current one is `metadata` so maybe `metadata2`)
> * [ ]  Spin up Postgres 13.1 container mounted to `metadata2` (maybe `db2`)
> * [ ]  `pg_restore` dump into `metadata2`
> * [ ]  Edit `docker-compose.yml` and `Dockerfile_pg` so that original `db` is built as 13.1 and mounted to `metadata2`
> * [ ]  Bring down `db2`, bring down `db`, rebuild and relaunch `db`

After 4 above, I would rather we use [this](https://github.com/gdiepen/docker-convenience-scripts/blob/master/docker_clone_volume.sh) (or at least use the commands there in) and delete the `metadata` volume, rename `metadata2` to `metadata`, rebuild and we are good to go.

Precautions;

- We need to have a back up of the entire set up as is, perhaps taking a new snapshot as @edwinmp did last time would come in handy again
- We may have to communicate to our users as there will like be a longer down time that usual (maybe we can totally avoid this with load balancing next time, as shutting down one DB at a time will be transparent to the end user)
- We need to be sure we have enough space on the server as it will basically mean having the space reduced by the size of the `metadata` volume three fold at some point i.e current `metadata` volume, backup from `pg_dumpall` and the restoration volume `metadata2`

**Comment by wakibi** [comment]
@k8hughes  I will need a day's work to finish this. Already some work has gone into the planning
