### ISSUE TITLE
New auto scheduled event run instances are created based on the previous run end time

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#421]
While the `date` should be based on the previous run's end date (in the event that a run goes on for too long), the `time` should be based on the previous run's start time. This will ensure start time consistency. Currently the start time gets later and later with each run.

**Comment by k8hughes** [comment]
@davidebukali  I think I've seen a PR connected to this... is that right?
If so can you move this to code review and link the PR.

**Comment by edwinmp** [comment]
This seem to be functional on staging
![image](https://user-images.githubusercontent.com/5672438/108235653-15658400-7157-11eb-8dbe-900450ed1962.png)
