### ISSUE TITLE
Update end-to-end testing to include core features

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#422]
- [x] Login
- [x] Query Builder (each function)
- [x] View query data
- [ ] Update data source

**Comment by edwinmp** [comment]
As with the documentation, updates to this will need to be made as we go. They'll especially be required on PRs that affect core features.

**Comment by edwinmp** [comment]
Adding end-to-end tests is now part of our expected deliverables for all work.

**Comment by edwinmp** [comment]
@ThatcherK doing this for viewing query data is a high priority. Also the recent feature @wakibi added requires end-to-end testing (issue #470.

**Comment by edwinmp** [comment]
@wakibi will you be adding the end-to-end tests for #470 yourself or should Thatcher do those as well?

**Comment by edwinmp** [comment]
@ThatcherK I've added APIs to the checkbox list in the issue's main comment as one of the deliverables ...

**Comment by wakibi** [comment]
> @wakibi will you be adding the end-to-end tests for #470 yourself or should Thatcher do those as well?

@ThatcherK can enjoy that one

**Comment by ThatcherK** [comment]
Noted

**Comment by edwinmp** [comment]
> @ThatcherK I've added APIs to the checkbox list in the issue's main comment as one of the deliverables ...

I've removed this.

**Comment by edwinmp** [comment]
@ThatcherK 
The freeze feature in question is found under:
`Data Sources` -> `Versions` -> `Freeze Current Version`
and
`My Datasets` or `Published Datasets` -> `Versions` -> `Freeze Current Version`

They'll naturally need to be tested separately as they have slightly different use cases.

The data sources freeze feature in issue #470 allows the created frozen dataset to appear as a data source, so you'll need to verify that it exists under the `Data Sources` page and that you can query it as you would a normal data source... I'd prefer to avoid interception here as much as possible as we'll be testing everything from creation to deletion.

The datasets freeze feature only supports creation, download & deletion (I think).

Manually test these to see what to expect.

**Comment by edwinmp** [comment]
@ThatcherK for the `Export to CSV` button:

1. Test that the button is visible and is a submit button
3. Test that the form has correct link in its action property and the correct method

![image](https://user-images.githubusercontent.com/5672438/116529253-6aefa700-a8e5-11eb-9326-4063a457a896.png)

This should be enough for now.

Reference:
[Cypress Docs](https://docs.cypress.io/faq/questions/using-cypress-faq#Is-there-a-way-to-test-that-a-file-got-downloaded-I-want-to-test-that-a-button-click-triggers-a-download) 

For when we need to actually verify the downloaded file's contents, look [here](https://github.com/cypress-io/cypress/issues/949)

**Comment by ThatcherK** [comment]
Okay
