### ISSUE TITLE
Move data update configs to separate repo to remove current dependency on code repo

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#424]
https://github.com/devinit/ddw-analyst-ui/tree/develop/data_updates/manual
@akmiller01 is this all the files? If not, could you please add links to all that we need to move for this, and any other info vital for this task.

**Comment by akmiller01** [comment]
Yes @edwinmp that's absolutely all of the static data files.

**Comment by edwinmp** [comment]
@davidebukali the steps below would lead to the least disruptive changes

- [ ] Create repo & copy files to it
- [ ] In dew repo, delete files & commit
- [ ] In ddw repo, add folder to .gitignore
- [ ] In ddw repo, copy files back so existing code doesn't break
- [ ] In ddw repo, add a new python file under the `data/management` path. Add the code that pulls updates from GitHub into the `manual` folder to your new management command file. (doesn't need to contain any validation at this point - just pull updates from GitHub)
- [ ] In ddw repo, add a new script under the `data_updates` folder. Trigger the management command above here - this will be used in a scheduled event & should allow us to manually or periodically pull updates from the new repo.
- [ ] Given how vital these files are, it'd be best to make sure this is triggered on first run. At the very least, you'll need to update the documentation, before any manual data updates are run

**Comment by edwinmp** [comment]
@devinit/di-devs the CSV files have been moved out of this repo into [this](https://github.com/devinit/ddw-data-update-configs) one. To fetch them into your local repo, run `docker-compose exec web python manage.py update_csv_files`
