### ISSUE TITLE
Cannot delete selected row in a previously saved filter.

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#442]
If I select a row in a filter and delete it, the bottom row is deleted, not the one I selected.
In this example I tried unsuccesfully to delete the row containing XI-IATI-EBRD. The bottom row containing 47122 was deleted.

![ddw error3](https://user-images.githubusercontent.com/3491562/108380121-772cf900-71fe-11eb-97dc-535787b33242.png)

**Comment by edwinmp** [comment]
A fix for this has been deployed. If it persists, clear your cache and try again.
