### ISSUE TITLE
"filter" command

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#45]

**Comment by Duncan-Knox** [comment]
Hi @akmiller01 and @edwinmp, I am testing a few text-search queries using 'contains'. It seems possible that 'contains' is set to 'equals', for example if I search for donor name 'United Kingdom' I will get return output. If I search for 'United' the data loads as 'No results found'. However, one may expect this to return any donors with United in their name (Kingdom, States and Arab Emirates).

If set to find words within cells, the 'contains' function will likely be applied by analysts to the longer project descriptions. Say searching for the word 'Pneumon' could filter in a project with a description of 'treatment of pneumonia' or 'advances in our understanding of Streptococcus pneumoniae infection'.

**Comment by Duncan-Knox** [comment]
I'd argue, if please possible, a setting which returns character strings unaffected by surrounding characters would be a preference, eg 'econ' would return 'macroeconomics', 'economy' 'micro-economics' and so on.

**Comment by Duncan-Knox** [comment]
Or as suggested by Dan.W a string and a character type wild card type option that the user can add in when searching.

**Comment by akmiller01** [comment]
This might be a bit of a disconnect between the front-end and the back-end. `contains` is a misnomer because it's just executing a SQL `ilike` command. Instead of `contains` I would call it `is like` maybe?

@Duncan-Knox if you want wildcards, you need to type them yourself `%united%`

**Comment by edwinmp** [comment]
I think people who aren't familiar with SQL would find this distinction between `contains` & `is like` confusing... Oh wait, I do find it confusing... is there one that results in the behaviour Duncan expects without the need for wildcards? Or do I need to add wildcards to all values under `contains`...

**Comment by akmiller01** [comment]
I think this is all contained under just one function. `text_search` right? Maybe we need a way of explaining how to use more complicated functions? I would hate to pare down its usefulness.

Right now you can use it like:
`united kingdom` only returns case insensitive exact matches.
`%united%` returns substring case insensitive matches.
`united kingdom|uganda` for exact matches joined by OR.
`united kingdom&uganda` for exact matches joined by AND.

Or any combination of the above.

**Comment by edwinmp** [comment]
With a clear example on usage, I'll add an `info` alert to the UI for this option.

**Comment by Duncan-Knox** [comment]
Have I completely mistaken the meaning of 'contains' in filter? Apologies for the confusion if so.

Would the scalar transform function 'text search' be the best go to option for undertaking word-searches on cells? I'd opted for the 'contains' filter as had thought the options here of adding multiple filters in a single query (working as 'or' commands between both columns and/or values) was quite well suited to this type of text searching. However if it is possible to use with | and & as Alex describes above then it sounds good. Would this also have the ability to find specific text within longer strings?

Had not realised about the % wildcard option for users. This is most useful if it is available. People should certainly be able to just add these in if needed.

**Comment by edwinmp** [comment]
@Duncan-Knox, could you please try out Alex's options for your search and see if they return the expected results.

**Comment by Duncan-Knox** [comment]
@edwinmp sure, will do so.

**Comment by Duncan-Knox** [comment]
I've tried out the options listed by Alex on Filter 'Contains' and Scalar Transform 'text search'. These queries have generally been on donor and recipient names in the CRS. The options all return the expected results, including in combination and with multiple entries, which is excellent.

**Comment by edwinmp** [comment]
Great, I'll add the info alert then, to offer help on the usage.

**Comment by Duncan-Knox** [comment]
The info alerts are a really good addition
