### ISSUE TITLE
Use freeze current version database in query builder interface

### ISSUE THREAD

**Issue by carichi** [devinit/ddw-analyst-ui#470]
GHA team priority - as FTS database updates daily, it would be extremely useful to be able to freeze the FTS Precoded database current version under 'data sources' and having that available to run queries on. The freeze functionality seems to work ok on 'My datasets' just to store the existing version as it is, but does not currently show as a database to use within the query builder interface.

**Comment by edwinmp** [comment]
@wakibi this seems to have been the original motivation for the freeze feature ... how difficult would it be to implement? I don't mind if it's something we add to the advanced query builder as long as it's possible somewhere.

**Comment by k8hughes** [comment]
We definately did discuss this as a need, specifically with GHA in mind - but we might not have planned to do it with the freeze feature.  It was in our planning for phase 2 features.  Lets discuss how we can make this work for the GHA team.

**Comment by k8hughes** [comment]
@wakibi can you update this issue with the detail for how it is going to function and a note about where you have managed to get up to?

**Comment by edwinmp** [comment]
@wakibi you'll need to add an entry for this in the documentation with details on its functionality and expected behaviour e.g naming convention of the frozen datasets

**Comment by edwinmp** [comment]
If there's any new sub-headings (I expect there will be), let me know so we can add them to the dropdown for the versions pages 

![image](https://user-images.githubusercontent.com/5672438/116543215-47812800-a8f6-11eb-87e8-13529ad56a7f.png)
