### ISSUE TITLE
Povcalnet update

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#475]
Zach flagged this data has been updated, can we pull the update into the DDW?

**Comment by k8hughes** [comment]
@akmiller01 I think this happened yesterday didn't it?

**Comment by akmiller01** [comment]
I triggered the update yesterday morning, it ran for about 10 hours but looking at the logs it seems to have encountered an error; so I may need to work on the code. the PovCalNetAgg and PovCalNetSmy tables finished, but PovCalNetP20 failed as well as PovCalNetDist.

**Comment by akmiller01** [comment]
The World Bank no longer provides a headcount for the world at certain threshholds... I'll have to ask Dan/Zach about this: http://iresearch.worldbank.org/PovcalNet/PovcalNetAPI.ashx?Countries=all&GroupedBy=WB&povertyLine=1.9&RefYears=all&Display=Regional&format=csv

**Comment by akmiller01** [comment]
Fixed the issues inline; we just won't have a P20 threshold in 2018/2019 while the WB omits that figure. PovCalNetDist is re-running now.

**Comment by akmiller01** [comment]
https://github.com/devinit/ddw-analyst-ui/pull/479
