### ISSUE TITLE
FTS cluster-sector mapping 

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#491]
This would map the columns Destination global cluster name and Destination cluster name in the FTS dataset against our own FTS cluster-sector classification for relevant food sectors. I see this working similarly to the available functionality of a Query Step - Left Join with the OECD CRS sector mapping dataset. So having this as a dataset available to Join with. Or alternatively, having this as an additional FTS code list which would generate an additional 1-2 columns in the FTS Precoded dataset. 

FAO project so use P0382 – FAO FCPR in focal point.

@carichi  to supply to dataset for @wakibi  to add a table.  

Next question is keeping this dataset up to date, there should only be changes to this infrequently. 
We could add it to the whitelisted tables so the GHA team can download and reupload when data is updated

**Comment by k8hughes** [comment]
This is just a few hours of dev work once the data has been shared.

**Comment by k8hughes** [comment]
@carichi Any update on this yet?

**Comment by wakibi** [comment]
@carichi do we have any updates on this?
