### ISSUE TITLE
FAO work:  4.	Run keyword searches  

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#493]
Finally, we’re looking at running some keyword searches on the project description column in the FTS dataset. I believe that this is currently possible by using a query type Filter with an operation of 'Contains' with case insensitive substring matches using % and multiple words using the | symbol. 

Our list of keywords are likely to contain up to 40-50 terms, and I was wondering if there would be a possibility of including an option to upload a list of keywords as a CSV?  ie a faster way of adding 50 key words.

Would this sit best in the advanced query builder?  @edwinmp ?  Can you suggest a time estimate for this work

to log time for this work FP code to use is P0382 – FAO FCPR

**Comment by edwinmp** [comment]
Hi @k8hughes ... this is not feature of the advanced QB, nor is it likely to be (anywhere really). I understand it maybe a bit tedious to do with >40 terms, but building this feature is more costly than its worth as the keywords would still need to be added to the CSV. I'd rather they be added directly to the QB, which now has a feature for duplicating similar filters (& we now duplicate steps), so it'll take less time to add it directly to the QB than it would via CSV.

**Comment by k8hughes** [comment]
@carichi  - so it seems this would be a bit difficult to build so you'll have to add the terms manually.  Hopefully you can do that and save the query?

**Comment by Duncan-Knox** [comment]
@carichi I usually do this in excel by listing the key terms in a spread sheet column and doing an =& formula to bring in the 'I' and '%' to wrap the key words, concatenating this and pasting into the box on the UI, have attached example in-case helpful. 
[Keywords for UI.xlsx](https://github.com/devinit/ddw-analyst-ui/files/6285862/Keywords.for.UI.xlsx)

**Comment by k8hughes** [comment]
OK, seeing as we don't need coding to fix this I am going to close the issue.
