### ISSUE TITLE
FAO issue:  Code the countries covered by the Global Report on Food Crises 

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#494]
This is a pretty straightforward one which would code the column Destination Country (Destination location name) or Destination ISO Alpha 3 in the FTS dataset with Y/N whether the respective country was included in the Global Report on Food Crises between 2016-2021, according to data shared with us by FAO.  Each year the report comes out and we want to see which countries have been included which years.

 Most recipient countries are included in the report over multiple years and it would be useful to be able to see that yearly breakdown. 

This can be added as another table that you can join to.  Any other code lists that the GHA team need then give us the data and we can add the tables.

@carichi and  @wakibi to discuss how to form this table depending on all the codelists that want to be include.

**Comment by carichi** [comment]
two other lists that we might want to upload this month: 2020 Protracted Crises Countries list and GHA 2021 Country ID - TBC

**Comment by wakibi** [comment]
@carichi find the FAO Classifications with the year [here](https://github.com/devinit/ddw-data-update-configs/blob/fao_food_crises/manual/fts_dependencies/fts_fao_classifications.csv)

**Comment by edwinmp** [comment]
@wakibi there's no PR linked to this ... is it done?

**Comment by wakibi** [comment]
Still waiting for this data from @carichi (or her guidance on way forward in case her team decided to do away with the extra data). 

> two other lists that we might want to upload this month: 2020 Protracted Crises Countries list and GHA 2021 Country ID - TBC
