### ISSUE TITLE
Create new remote test database

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#50]

**Comment by akmiller01** [comment]
@edwinmp and @Napho while we're waiting on a DO account, shall we discuss requirements for the server here? The pricing for all the services are here: https://www.digitalocean.com/pricing/ I imagine for dev purposes we can start with the $5 server and work our way up from there. Worth looking into the standalone psql services, but they start at $15 for only 10 GB where the $5 droplet comes with 25 GB and can be upgraded to 80 GB for $15.

**Comment by Napho** [comment]
@akmiller01 convenience always comes at a price (managed services). The flexibility that managing your own database gives you is also always much greater, for example on azure you cant run copy on postgre, you have to first move the data to azure table storage with powershell, then export from table storage. I haven't tried DO's but im guessing it comes with its big limitations too. I do agree we can start with the $5 dollar test droplet and have everything in containers on it. Its what i had in mind anyways ...

**Comment by akmiller01** [comment]
Using docker as test database, as well as having setup DO account.
