### ISSUE TITLE
Filtering by data source returns the correct data but the datasets are showing the wrong data sources

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#535]
In the screenshot below, the filter is for IATI and the datasources are IATI, but some are showing their source to be FTS or OECD

NB: something's up with GitHub... I failed to upload the screenshot ... do a manual test

**Comment by edwinmp** [comment]
This is still happening on live

**Comment by wakibi** [comment]
Going to deploy this to live.

**Comment by wakibi** [comment]
> Going to deploy this to live.

Done
