### ISSUE TITLE
Add SQL Editor to the Advanced QB

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#542]
- [x] Add widget to toggle the GUI and SQL views
- [x] In SQL view, show a text editor
- [x] Show preview window beneath the text editor
- [ ] Add support for variables managed by place holders
- [x] The the right of the view, show schema with all tables and their columns (searchable)

![image](https://user-images.githubusercontent.com/5672438/121260623-3bf02c00-c8ba-11eb-89ac-79f65d85c484.png)

**Comment by k8hughes** [comment]
@edwinmp is this on staging?  if so please tag @dean-breed for a functional review
