### ISSUE TITLE
Advanced Query Builder : Multiple Filters

### ISSUE THREAD

**Issue by JennyR-DI** [devinit/ddw-analyst-ui#580]
Can you please advise the best way to create an advanced query containing multiple filters?

When I've tried adding a second filter I get either a JSON error message about an 'invalid token' or a curly bracket. Please let me know if there are any adjustments I need to do in the 'Clause Config' before inserting a second filter.

In SQL I would like to do something along the lines of:
SELECT * FROM DAC2b WHERE year > 2000 AND (donor_name = 'DAC Countries, Total' OR donor_name = 'Multilaterals, Total');

**Comment by edwinmp** [comment]
Closed in favour of #531
