### ISSUE TITLE
Make changes to columns in the IATI PUBLISHERS table

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#585]
**Delete All Exisiting Columns**

**Add**

- Reporting Organisation Reference
- Registry Id
- Organisation Type
- Organisation Name
- Abbreviation
- Usability Score
- Tracker Commit
- Tracker Spend
- Latest Transaction Year
- HQ Country
- CRS Codes
- IATI Organisation Type
- IATI Organisation Name

Here is a description of each column

[IATI Publishers Table Metadata.xlsx](https://github.com/devinit/ddw-analyst-ui/files/7219592/IATI.Publishers.Table.Metadata.xlsx)

And here is the new datafile that shoule be loaded at the outset

[IATI Publishers Master.xlsx](https://github.com/devinit/ddw-analyst-ui/files/7219601/IATI.Publishers.Master.xlsx)

**Comment by k8hughes** [comment]
2hrs work

**Comment by wakibi** [comment]
@akmiller01  Corresponding data PR [here](https://github.com/devinit/ddw-data-update-configs/pull/8)

**Comment by bill-anderson** [comment]
Checked. All good. Happy to close.
