### ISSUE TITLE
Add Columns to IATI TRANSACTIONS table

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#586]
Donor Transaction Type
Original Transaction Value USDm

**Comment by bill-anderson** [comment]
These are the output labels. I think we have a different naming convention for DB columns - indicating that they are calculated fields. (Do we still??)

**Comment by wakibi** [comment]
@bill-anderson yes, they start with `x_...`

@akmiller01 data PR [here](https://github.com/devinit/ddw-data-update-configs/pull/9)

**Comment by bill-anderson** [comment]
Checked. All good. Happy to close
