### ISSUE TITLE
Advanced Query Builder - Adding Multiple JOINs

### ISSUE THREAD

**Issue by JennyR-DI** [devinit/ddw-analyst-ui#591]
I've been trying to add ISO code information to both the Donor and Recipient columns in the 'OECD DAC2B: OOFs and export credits' dataset.
I can add the first LEFT JOIN no problem:
![image](https://user-images.githubusercontent.com/90774534/134512886-5fb397d9-2487-492a-9c3c-1edb2a054d50.png)

But I can't add a second LEFT JOIN to obtain the ISO values for the 'Recipient Code' column.  Can you please advise how I can add two JOINS in a query?

I've tried saving the query after the first JOIN and then editing it to add the second JOIN but this hasn't worked for me so far.

**Comment by edwinmp** [comment]
@JennyR-DI we don't yet have support for multiple joins ... I'll mark this ticket as a feature request.

**Comment by JennyR-DI** [comment]
Thanks Edwin for clarifying that, that's good to know I shouldn't do multiple joins now.

**Comment by wakibi** [comment]
Adding for emphasis so we do not get, this includes multiple self joins i.e same table being joined more than once

**Comment by k8hughes** [comment]
@davidebukali  and @edwinmp can you tag @JennyR-DI or @dean-breed when this is on staging for testing

**Comment by davidebukali** [comment]
@JennyR-DI this is ready for testing on [staging](https://staging-ddw.devinit.org/)
