### ISSUE TITLE
Advanced Query Builder - Group By Step

### ISSUE THREAD

**Issue by JennyR-DI** [devinit/ddw-analyst-ui#592]
I was trying to use the Group By step to aggregate a dataset but I keep getting the following error:
![image](https://user-images.githubusercontent.com/90774534/134688729-f89d8224-01f6-4373-8e04-8126523ac4f7.png)

Is it possible to use the Group By step to get the overall sum for a categorical column in a dataset, such as for the dataset 'OECD DAC2B: OOFs and export credits' I would like to find the total 'Value' per the 'Aid Type Name' column, or, to find what the maximum/minimum value is per 'Aid Type Name'?

**Comment by JennyR-DI** [comment]
Apologies but I can't seem to add this Issue to the Phase Two Features projects - when I click Projects nothing happens.

**Comment by davidebukali** [comment]
@JennyR-DI I am not able to reproduce this bug on ddw staging; Could you kindly share a link to the query you created for more testing

**Comment by edwinmp** [comment]
@davidebukali the `group by` is not currently available on staging or live, so Jenny can't begin to try to replicate it ... besides, @ThatcherK is currently working on the Group By & Having clauses so she's best placed to deal with this. This wasn't in our backlog anyway ... I suggest u pick the join.

**Comment by edwinmp** [comment]
[Here's](https://github.com/orgs/devinit/projects/2/views/5) the active sprint backlog

**Comment by davidebukali** [comment]
Thank you for the clarification @edwinmp

**Comment by k8hughes** [comment]
@davidebukali and @edwinmp where did this get to?  Can someone update this issue with the status

**Comment by edwinmp** [comment]
I don't think this is still happening. Please reopen if it is.
