### ISSUE TITLE
Create slack channel and integration for admin email errors

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#598]
@akmiller01 @wakibi I hope this would do the trick, cutting down on the clutter in our main emails. I'll share the credentials for this so u can add it to your email clients. Sure we can use it for all our projects.

**Comment by wakibi** [comment]
@edwinmp I had asked IT to create di-devs@devinit.org (it's a mailing list with the Kla Devs only as members for now). Isn't possible to use that and filter emails in our clients?

**Comment by edwinmp** [comment]
@wakibi that's still going to send to our DI emails, and that's what we're trying to eliminate.

**Comment by wakibi** [comment]
@edwinmp as an alternative, how about going nuts and creating slack integration for these notifications so they are sent to a slack channel that we can choose? I mean if the issue is email, then I would rather we completely avoid email and use an alternative medium that will be much easier to manage. Your thoughts?

**Comment by edwinmp** [comment]
I'm for that ... we had some other webhooks earlier on but slack management became rather strict on what addons to have & I got lazy to jump through those hoops - plus I didn't have the time ... go nuts :)

**Comment by wakibi** [comment]
Changing title for this consequently

**Comment by k8hughes** [comment]
@wakibi to test and close if working

**Comment by edwinmp** [comment]
@wakibi close if done.

**Comment by edwinmp** [comment]
Moving to `Backlog` for clarity during the next sprint planning.

**Comment by wakibi** [comment]
This was deployed to production. Check slack channel #auto-errors
Closing as done
