### ISSUE TITLE
SDGs

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#616]
I haven't been able to find any usable table of SDG goals, targets and indicators anywhere and have had to build it myself. It is worth keeping these as master copies in DDW. 
[SDG Masterlist.xlsx](https://github.com/devinit/ddw-analyst-ui/files/7925187/SDG.Masterlist.xlsx)

**Comment by k8hughes** [comment]
@wakibi can we get this on DWW? 
The options are whether this one table or three....

**Comment by wakibi** [comment]
@bill-anderson this has been deployed on staging. Peruse through and confirm all is good and I shall deploy on live as well.

**Comment by bill-anderson** [comment]
I would put the Goal number into the Indicator Table as well. If I am working with indicators and want the goal description I need to do a double join (first to target and then to goal) right?

**Comment by wakibi** [comment]
@bill-anderson that's right. Like we discussed in that call, I completely normalised the data.

**Comment by edwinmp** [comment]
@wakibi was this done?

**Comment by k8hughes** [comment]
This has been done. @bill-anderson maybe if you work with the data you can come back with specifics for what we might need to change.
