### ISSUE TITLE
Shuffle of step_ids

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#617]
Having moved steps around, when deleting any step, the step order seems to either: (1) return to the original; or(2) shuffle in another way. I believe it is the former but not certain.

**Comment by dean-breed** [comment]
Taken a deeper look - it definitely isn't the original order which is extremely strange!

**Comment by ThatcherK** [comment]
Hi @dean-breed , please provide clear steps to replicate this bug for easier troubleshooting

**Comment by dean-breed** [comment]
@ThatcherK I can't recreate this anymore so no worries! I'll reopen if it happens again
