### ISSUE TITLE
IATI transaction problem - XDR conversion

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#618]
AfDB (XM-DAC-46002) publish all values in XDR and currently the US conversion is failing. Not clear if this is only an XDR problem or for more currencies

**Comment by akmiller01** [comment]
For any particular year, @dean-breed ? We'll need to add conversion rates for XDR in 2022 if you want the new values to convert.

**Comment by akmiller01** [comment]
Incidentally, I've already done this for the IATI annual report. Updated from IMF.
[ex_rates.zip](https://github.com/devinit/ddw-analyst-ui/files/7941532/ex_rates.zip)

**Comment by akmiller01** [comment]
And of course those only represent the 2022 XDR exchange rates as of Jan 19 or so. It fluctuates on a daily basis. But maybe we can aim to update it once per quarter or something.

**Comment by dean-breed** [comment]
Where is the location of the ex_rates @akmiller01? Can we update as part of the ETL process to stop it happening in future?

**Comment by dean-breed** [comment]
It is worth mentioning that ALL afdb transactions have not converted so there is clearly an issue that is not 2022-focused @akmiller01

**Comment by akmiller01** [comment]
Here's where the exchange rates are: https://github.com/devinit/ddw-analyst-ui/blob/develop/data_updates/Python/iati_exchange_rates.json

**Comment by akmiller01** [comment]
Conversion is working fine as far as I can see, @dean-breed . Are you use it's `XM-DAC-46002`?

```
select x_currency, x_transaction_value, x_transaction_value_usd from repo.iati_transactions where reporting_org_ref='XM-DAC-46002' and x_transaction_year=2020;
```

![image](https://user-images.githubusercontent.com/2836840/151163945-e9f0025d-55d4-42a6-91de-c8721cf886b7.png)

Do you have an example of an IATI identifier that's not working?

**Comment by dean-breed** [comment]
I see - it is working for all pre-2021 tramsactions because there are 0s in the 2021 and 2022 ex_rates @akmiller01

**Comment by akmiller01** [comment]
Would be nice to eventually automate it. But since it's combining multiple data sources that come in XLSX, it's a manual update for now https://github.com/devinit/ddw-analyst-ui/pull/619
