### ISSUE TITLE
Point Spotlights API to DDW DB

### ISSUE THREAD

**Issue by wakibi** [devinit/ddw-analyst-ui#624]
Spotlights data was copied to the DDW, but the API still reads from the old DB. This will make the API point to the DDW DB as well, so we can deprecate the old DB

**Comment by edwinmp** [comment]
@wakibi what's the status of this? I gather there's no code to review :)

**Comment by wakibi** [comment]
[PR](https://github.com/devinit/ddw-external-api/pull/33) is here, different repo. Thought I had tagged you on the PR?!

**Comment by edwinmp** [comment]
With this many repos, stuff gets lost in emails sometimes :)

**Comment by k8hughes** [comment]
@wakibi and @edwinmp can you update where we got to with this issue?  hopefully it is close to being finished?  If review is needed can you tag @dean-breed and make it clear what he needs to test

**Comment by k8hughes** [comment]
@wakibi @edwinmp  can you update this issue please...

**Comment by edwinmp** [comment]
@wakibi I commented on the PR for this a long time ago, specifically that I couldn't test it so I'd trust that you have. Merge & close if confident it's done.

**Comment by edwinmp** [comment]
@wakibi close if done.

**Comment by edwinmp** [comment]
Returning to `Backlog` for clarity during next sprint planning.

**Comment by wakibi** [comment]
This was deployed to both staging and production. I just took time to verify and confirm. Closing
