### ISSUE TITLE
Select or reordering columns via the drag & drop feature removes existing aggregation

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#641]
Steps to reproduce

1. Open the Advanced Query Builder for creating a new dataset
2. Select a data source e.g. `Financial Tracking Service`
3. Check the `Select` clause
4. Under the select clause, uncheck `Select all`
5. Click `Select Column(s)` and select a numerical column e.g.`Amount USD`
6. Click the `Aggregate` button and add any aggregation e.g. `Sum`
7. Confirm under the config preview that the aggregation is present
8. Return to selecting columns and select another
9. Confirm under the config preview that the aggregation is no longer present
10. Replace the aggregation (make sure to confirm its there under the config preview) and then reorder the columns
11. Confirm that the aggregation is no longer present.

**Comment by ThatcherK** [comment]
@edwinmp , on my end, at step 9, I still have the aggregate, but i get a maximum depth reached error, I guess that's another bug to solve..
The aggregate disappears each time i click the order columns button

**Comment by k8hughes** [comment]
@ThatcherK is this on staging?  If so can you tag @dean-breed for testing?

**Comment by ThatcherK** [comment]
Yes this is already on staging, @dean-breed could you test this out?

**Comment by dean-breed** [comment]
This bug no longer occurs. All good to go live!
