### ISSUE TITLE
Replace JQuery Query Builder with React Query Builder

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#643]
https://react-querybuilder.js.org/
Any alternative to JQuery is welcome, especially if it's React. This is an alternative that's easy to customise.

**Comment by edwinmp** [comment]
A fully configured component is already available in [this](https://github.com/devinit/ddw-analyst-ui/tree/feature/having-clause) branch

**Comment by k8hughes** [comment]
@ThatcherK what stage did this get to?  Hopefully we can get it released soon?

**Comment by ThatcherK** [comment]
@k8hughes , this was merged into  the main branch

**Comment by k8hughes** [comment]
@ThatcherK if it has been merged then should the issue be closed?

**Comment by ThatcherK** [comment]
Yes it should

**Comment by k8hughes** [comment]
Can you change the staus to reflect if it needs testing on staging or if it has been released to live already and should be closed?

**Comment by ThatcherK** [comment]
Tested this on staging, and the having clause seems to be distorted, looking into it

**Comment by edwinmp** [comment]
@ThatcherK mine looks fine ... could you please share a screenshot of yours

**Comment by ThatcherK** [comment]
<img width="1327" alt="Screenshot 2022-04-12 at 10 15 27" src="https://user-images.githubusercontent.com/32189973/162902834-062ed3c7-202c-4e99-8e1d-10c4e66fc9d5.png">
I expect the value field here to be a drop down....

**Comment by ThatcherK** [comment]
This is done, and it's on staging, am going to create another ticket to remove the undesired behaviour in the having clause
