### ISSUE TITLE
Create data update pipeline for the Gates dashboard

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#647]
Currently, the CSV files are generated manually for OECD, and the IATI pipeline still has some manual elements. Dean has already done most of the work for the IATI in PR #628  & we just have to do the same for OECD.

**Comment by edwinmp** [comment]
A fully configured component is already available in [this](https://github.com/devinit/ddw-analyst-ui/tree/feature/having-clause) branch

**Comment by k8hughes** [comment]
@ThatcherK is this nearly ready to release?  I think IATI is done and OECD is still to do - is that right?

**Comment by k8hughes** [comment]
@dean-breed can you also follow up this one so we know the dashboard is updating

**Comment by dean-breed** [comment]
We need the [shell file](https://github.com/devinit/ddw-analyst-ui/blob/feature/iati-gates/data_updates/iati_transactions.sh) to be pulled into master if everyone is happy

**Comment by ThatcherK** [comment]
I am going to make a few more edits for the csv file names, make releases and test if the changes work well without breaking the charts.

**Comment by dean-breed** [comment]
Great, thanks @ThatcherK

**Comment by ThatcherK** [comment]
This is done, the files have been tested on the live site, nothing is broken

**Comment by dean-breed** [comment]
Thanks @ThatcherK

**Comment by ThatcherK** [comment]
@dean-breed , hadn't yet been merged
