### ISSUE TITLE
Update to FE needed to get new 'country' field

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#649]
Currently, when updating the IATI publishers table on DDW UI, there is still no new 'country' field (note: I am not referring to the HQ country field).

**Comment by edwinmp** [comment]
@dean-breed this is done, but how soon do you need it deployed?

**Comment by wakibi** [comment]
@edwinmp deploying can be done at leisure. I already run a data update for this via the backend, so @dean-breed has all the data he needs.

**Comment by edwinmp** [comment]
Excellent ... wanted to bundle it with a few other updates and deploy them all at once.

**Comment by k8hughes** [comment]
@edwinmp is this deployed? If on staging can we tag @dean-breed  for testing
