### ISSUE TITLE
Dataset filter by data source doesn't return AQB datasets

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#651]
**Steps to Reproduce**

1. Click on `My Datasets` on the sidebar
2. Ensure you have datasets created via the Advanced Query Builder
3. Click `Filter by data source` and select a matching data source to one on an AQB query
4. See bug i.e. Query will not show up in results

**Comment by edwinmp** [comment]
Will be deployed in the next release.

**Comment by k8hughes** [comment]
@edwinmp will it be possible to get this on staging in the next release?  Might be good to get a release out soon so that we don't get merg conflicts.

**Comment by edwinmp** [comment]
Merge conflicts are rare and easy to deal with @k8hughes ... no worries - will deploy all this tomorrow.
