### ISSUE TITLE
Slow loading times

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#657]
The DDW UI has been slow for quite a while and doesn't seem to have got better. It would be good to know why this is if we are going to encourage others to make more use of it. It could be much worse on IATI data as that is mostly what I use.

**Comment by dean-breed** [comment]
@wakibi I think it is just when the SQL queries are built quite inefficiently from the UI as we discussed previously. I will try tackling it with a direct SQL query when I next come across it.

The API pulls are also slow on all queries, even if it loads fast on the UI. Is this a problem that can be fixed? Or not? We noticed this a lot in the RHFP work.

**Comment by edwinmp** [comment]
@dean-breed could you share a link for a particularly slow dataset ...  I think you did a while back but can't find it - want to recreate it via the Advanced QB and compare the speeds.

**Comment by k8hughes** [comment]
The issue is when exporting something really big, all the user sees as a response is the page loading for a while, this can make them think nothing is happening - could we explore having a progress bar to make it clearer for users.

**Comment by wakibi** [comment]
Hi @k8hughes, been investigating this. This is affecting IATI transactions and at the export level, as all data has to be pulled out of the DB before export starts. Will start implementing the progress bar once again.

@dean-breed you mentioned it was affecting the API as well. For this, the only way to improve the API side is improving query performance. You will have to come up with the fields that are filtered by mostly in the IATI transactions table, so we create indexes for those fields. That should improve performance considerably.

**Comment by dean-breed** [comment]
Thanks for taking a look at this @wakibi

So, if I understand you rightly, I should provide you with the most commonly used fields for filtering. We can then index them to improve performance?

**Comment by wakibi** [comment]
> Thanks for taking a look at this @wakibi
> 
> So, if I understand you rightly, I should provide you with the most commonly used fields for filtering. We can then index them to improve performance?

@dean-breed that's correct. I will go through all current IATI queries and see if I can find the columns that appear most in our queries

**Comment by wakibi** [comment]
> Hi @k8hughes, been investigating this. This is affecting IATI transactions and at the export level, as all data has to be pulled out of the DB before export starts. Will start implementing the progress bar once again.
> 
> @dean-breed you mentioned it was affecting the API as well. For this, the only way to improve the API side is improving query performance. You will have to come up with the fields that are filtered by mostly in the IATI transactions table, so we create indexes for those fields. That should improve performance considerably.

@k8hughes on second thought, we should keep this ticket strictly to handle query optimisation . There is another issue for estimating time for a query. That should be used to handle progress bar.

**Comment by dean-breed** [comment]
Agreed @wakibi - I have created a separate issue [here](https://github.com/devinit/ddw-analyst-ui/issues/665) to deal with the progress bar!

**Comment by dean-breed** [comment]
If you could let me know which fields are used the most, that would be wonderful. I can probably guess too though!

**Comment by edwinmp** [comment]
@wakibi what of caching? Queries could be slow in the beginning, but caching (with the likes of Redis) should solve runtime for subsequent attempts of the same query.

There's this informative [Whitepaper](https://docs.aws.amazon.com/whitepapers/latest/database-caching-strategies-using-redis/database-caching-strategies-using-redis.pdf) on it

**Comment by wakibi** [comment]
@edwinmp ohh yes, I have looked at that already, but I think caches are designed for frequently accessed data. In our set up, a query is accessed today. And it could be accessed again tomorrow. Still looking into this nevertheless.
