### ISSUE TITLE
How to move the DAC tables and CRS info into the DDW

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#66]
Naphlin to document here.

**Comment by k8hughes** [comment]
@Napho can you pop a note on here with handover info please?
@akmiller01 do you have what you need if we need to launch this whilst Naphlin is on paternity leave?

**Comment by akmiller01** [comment]
Hey @Napho I set up a structure here https://github.com/devinit/ddw-analyst-ui/tree/feature/data-collection-folder.

One data_updates folder, with subfolders R and Python. Shell scripts in the main folder to run either R or Python scripts, so eventually we can switch everything over to Python without breaking the flow.

If you can pop any scripts in there, commit it, and push it, I can work on cleaning them up and getting them to work with the file structure.

**Comment by Napho** [comment]
@akmiller01 i have pushed up merged scripts that are required to successfully load oecd mirrors, lots of edits required for us to finish it up, point of entry is data_updates/oecd.sh

**Comment by k8hughes** [comment]
@akmiller01 is there any reason for us to be keeping this as an open issue?

**Comment by akmiller01** [comment]
> @akmiller01 is there any reason for us to be keeping this as an open issue?

Wow, no; we've had the OECD files implemented for a long time.
