### ISSUE TITLE
Query and frozen dataset clean-up

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#662]
**Query clean up**

- Use a script to check any queries not used in the last 6 months, check with R&A team for any they would like to retain and then delete all.
- Create an automated process that contacts the query creator via email once it has been inactive for 6 months, allowing them to click a link if they wish to retain it.

**Frozen datasets**

- Use a script to check any frozen datasets created more than 6 months ago, check with R&A team for any they would like to retain and then delete all.
- Create an automated process that contacts the frozen dataset creator via email once it has been inactive for 6 months, allowing them to click a link if they wish to retain it.

**Comment by k8hughes** [comment]
this links #663 so whoever is working on this one needs to understand what is done for 663

**Comment by k8hughes** [comment]
Go by the data it was last used, not by date it was created.

**Comment by k8hughes** [comment]
This could be split into smaller issues so this can be delivered by a few people.

**Comment by edwinmp** [comment]
The PR for this has simply failed to close, not sure why.
