### ISSUE TITLE
Split out frozen data sets from source data

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#663]
Split frozen datasets away from the source datasets in the selection menus. Create two separate options and/or put frozen datasets at the bottom of the selection menu, whichever is easiest.

**Comment by k8hughes** [comment]
@wakibi can you see if this breaks into two tickets - or if one can you add some more details so it is clear for whoever does the work?

**Comment by wakibi** [comment]
@dean-breed would you still want the frozen datasets to be queried? Or only downloaded?

**Comment by k8hughes** [comment]
In the query builder there needs to be a check box where a user can select which drop down they see.
Options:
* Source data sets
*  Frozen data sets
Once a user selects from these options the appropriate drop down menu will be available.

In the data source menu there two types of data sets also need to be split out.  So as a user when I go to browser the data sets in the DDW I can select if I want to see source data or frozen data then, the page returned will show only one of these types. - This work is in issue https://github.com/devinit/ddw-analyst-ui/issues/687 

This is the issue for the query builder.

**Comment by dean-breed** [comment]
@wakibi We briefly discussed this over slack but the issue in #687 is exactly what I mean, yes.

**Comment by davidebukali** [comment]
@dean-breed this is ready for testing on [staging](https://staging-ddw.devinit.org/)

**Comment by dean-breed** [comment]
I've had a play around with this and it looks good to me! Happy to go ahead and deploy live the next time we do @davidebukali

**Comment by davidebukali** [comment]
Thank you @dean-breed
