### ISSUE TITLE
User guide link on DDW site

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#664]
Somewhere on the 'My Datasets' tab, preferably at the top, it would be useful to have a link to the user guide. Then, inexperienced users can clearly find the guide before using the DDW

**Comment by k8hughes** [comment]
Changing the ? icon to a button that says "user guidance" - same behaviour with the drop down menu that links to the google doc

@dean-breed does this sound like enough?

**Comment by dean-breed** [comment]
Yes, I think so @k8hughes - then, we can present in the R&A meeting to explain that's where it is held too

**Comment by edwinmp** [comment]
@dean-breed deployed the update for this to staging - take a look when u can. Let us know if you'd prefer the button the current grey or thematic red (see screenshot).

<img width="436" alt="image" src="https://user-images.githubusercontent.com/5672438/170212491-88c21777-cac3-42d0-90ef-0e1b74d5de2d.png">

**Comment by dean-breed** [comment]
Hi @edwinmp - the grey is fine and I think it's really good! Happy to merge

**Comment by edwinmp** [comment]
@dean-breed this has been deployed live.
