### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by dean-breed** [devinit/ddw-analyst-ui#665]
When exporting something really big, all the user sees as a response is the page loading for a while, this can make them think nothing is happening - could we explore having a progress bar to make it clearer for users. This is noticeable on use of the iati transactions table

**Comment by k8hughes** [comment]
Just show a loading indicator, not a count down - keep it simple

**Comment by dean-breed** [comment]
This is fine by me - let me know if you have any further questions @wakibi @edwinmp

**Comment by davidebukali** [comment]
@dean-breed when you get the chance, this is ready for testing on [staging](https://staging-ddw.devinit.org)

**Comment by dean-breed** [comment]
@davidebukali I have taken a look at this and I am not sure the behaviour is working for large datasets. When I try to download https://staging-ddw.devinit.org/queries/data/793, it does the exporting wheel then when it gets to the save progress bar, it is an empty csv. This isn't happening on other files such as https://staging-ddw.devinit.org/queries/data/783

I am not yet clear whether this is an issue with that one query or the progress bar as a whole

**Comment by davidebukali** [comment]
@dean-breed thanks for running these tests. This is a bug affecting large datasets, Ive created an issue #721; We are working on a fallback to using the old method of downloading for larger datasets until we fix this bug.

**Comment by dean-breed** [comment]
Thank you for the update @davidebukali
