### ISSUE TITLE
Frozen data sets split from source data in the data sources view

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#687]
In the data source menu there two types of data sets also need to be split out.  So as a user when I go to browser the data sets in the DDW I can select if I want to see source data or frozen data then, the page returned will show only one of these types.

https://github.com/devinit/ddw-analyst-ui/issues/663

**Comment by edwinmp** [comment]
I've deployed this but there's one thing I forgot about ... Frozen Data Sources shouldn't have the option to get frozen, so the `Versions` button shouldn't be visible on that view. I'll create a separate ticket for it.
