### ISSUE TITLE
Gulp not found when building JS files under deploy step in git actions

### ISSUE THREAD

**Issue by davidebukali** [devinit/ddw-analyst-ui#690]
See [this](https://github.com/devinit/ddw-analyst-ui/runs/6386821613?check_suite_focus=true) action for detailed error
<img width="773" alt="Screenshot 2022-05-12 at 10 00 41" src="https://user-images.githubusercontent.com/1607276/168011108-e0275304-7e9e-4798-8605-0a3ec3350942.png">

**Comment by edwinmp** [comment]
It would also be nice if the deploy step didn't return a successful response when this step fails. We keep missing it thinking everything went fine.

**Comment by wakibi** [comment]
This is hard to spot with no errors reported. Damn!

**Comment by edwinmp** [comment]
`Gulp not found` issue is fixed - what's pending on this is for it to NOT fail silently. Moving back to ToDo

**Comment by edwinmp** [comment]
Would also be nice to echo the `npm` and `node` versions as a step of its own - helps with troubleshooting.
