### ISSUE TITLE
File Not Found error on IATI RHFP update

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#699]
Error message below:

```
Traceback (most recent call last):
 File "data_updates/Python/iati_rhfp.py", line 88, in <module>
   data.to_csv("csv/IATI-RHFP-data-v1.csv", encoding='utf-8', index=False)
 File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
   storage_options=storage_options,
 File "/usr/local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
   csv_formatter.save()
 File "/usr/local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
   storage_options=self.storage_options,
 File "/usr/local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
   newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'csv/IATI-RHFP-data-v1.csv'
```

This happened during the `iati.sh` ETL script execution... Since it executes last, I don't think it affected the actual update process but I still stuck a `High Priority` tag on it as each update run will be marked as `errored` until it's fixed.

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/5672438/169215824-3b2892fc-c2ab-4c77-b306-bd5cfac3e108.png">

**Comment by dean-breed** [comment]
https://github.com/devinit/ddw-analyst-ui/pull/700 will fix this

**Comment by wakibi** [comment]
Safe to close this @edwinmp @dean-breed? PR has already been merged (and released with yesterdays release, right?)

**Comment by dean-breed** [comment]
Seems to have [run well ](https://github.com/devinit/di-website-data/commits/main/2022)- good to close in my opinion!

**Comment by wakibi** [comment]
Ahh... That commit was for the OECD script. We shall need to run the IATI RHFP one manually. It's run as part of IATI ETL, right?

**Comment by dean-breed** [comment]
Yeah, you're right. Why does it have to be triggered manually? Shouldn't it just be automatically run as part of the iati.sh?

**Comment by wakibi** [comment]
Yes, it does, but that runs every Monday I think. We can't wait for Monday (we are just from Monday). So I have to sort of simulate it and be sure it's working fine before closing this. On it already... Let me handle.

**Comment by wakibi** [comment]
Not closing this, error is still persistent. 

```
root@817693d48ba9:/src# python data_updates/Python/iati_rhfp.py
Traceback (most recent call last):
  File "data_updates/Python/iati_rhfp.py", line 89, in <module>
    data.to_csv("iati_csv/IATI-RHFP-data-v1.csv", encoding='utf-8', index=False)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/usr/local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/usr/local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/usr/local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'iati_csv/IATI-RHFP-data-v1.csv'
root@817693d48ba9:/src# 
```

**Comment by dean-breed** [comment]
My bad - needed folder creation - https://github.com/devinit/ddw-analyst-ui/pull/705

**Comment by edwinmp** [comment]
@wakibi IATI runs everyday at 4am - but you'll still need to trigger it manually (don't forget to delete the manual instance or it'll run daily at that time). I also mentioned during standup yesterday that this was still breaking. We need to be able to test this on staging so perhaps deploy a new snapshot of live. @dean-breed's PR above may as well include #704.

**Comment by edwinmp** [comment]
@dean-breed this has been deployed live and can confirm it's fixed.

**Comment by dean-breed** [comment]
Amazing! Thanks @edwinmp
