### ISSUE TITLE
Large datasets fail to export

### ISSUE THREAD

**Issue by davidebukali** [devinit/ddw-analyst-ui#721]
This was reported [here](https://github.com/devinit/ddw-analyst-ui/issues/665#issuecomment-1154977135)

Screenshots of the bug below:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/1607276/174000570-88011325-7f4f-46d4-b4c4-1936c5628019.png">
<img width="537" alt="image (1)" src="https://user-images.githubusercontent.com/1607276/174000600-cc7bb364-2e70-4154-999b-d5e5194ac7ac.png">

**Comment by edwinmp** [comment]
Obsolete since we removed this progress feature
