### ISSUE TITLE
US$ deflators constant 2017 master

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/ddw-analyst-ui#74]
[Deflators US$ 2017 constant prices 03-04-2019.xlsx](https://github.com/devinit/ddw-analyst-ui/files/3043665/Deflators.US.2017.constant.prices.03-04-2019.xlsx)

**Comment by Duncan-Knox** [comment]
Moving back to 'to do' as the data could be re-shared with the IMF WEO April 2019 version.

**Comment by Duncan-Knox** [comment]
Deflators for 2017 updated using the April 2019 WEO and DAC data updates.

[US$ deflators 2017 April 2019 WEO.xlsx](https://github.com/devinit/ddw-analyst-ui/files/3153067/US.deflators.2017.April.2019.WEO.xlsx)

Ready and waiting for re-load into DB at a convenient time.

**Comment by akmiller01** [comment]
Reshaped the data, can you check it over for any glaring mistakes @Duncan-Knox ?

https://github.com/devinit/ddw-analyst-ui/blob/data_updates/data_updates/manual/CSV/di_deflators_2017.csv

Also, I might hold off on reloading the data if you have some other pieces incoming soon, if that's alright.

**Comment by Duncan-Knox** [comment]
Hi @akmiller01 sure I'll check over. Yes will do some work on the government revenue data this week. Could wait until this is submitted, possibly the most recent update of the CRS could go in with these at the right moment?

**Comment by Duncan-Knox** [comment]
The NA bug has cropped up again in the processed version.

**Comment by akmiller01** [comment]
Good catch! Just pushed a fix at the same link above.

**Comment by Duncan-Knox** [comment]
Ok. Picking up country naming as CÃ´te d'Ivoire and SÃ£o TomÃ© and PrÃ­ncipe. Just making sure that these are not going through in such as way at your end (say it is just a setting on my side)?

Also have noticed the country name Eswatini has reverted to Swaziland. Might be one to fix if we've agreed to go with the former on country naming [edit].
