### ISSUE TITLE
All resource flows

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/ddw-analyst-ui#78]
[International resource flows 23-04-2019.xlsx](https://github.com/devinit/ddw-analyst-ui/files/3107934/International.resource.flows.23-04-2019.xlsx)

**Comment by Duncan-Knox** [comment]
Hi @akmiller01 when you get a mo please can you edit the source of this one from 'United Nations Conference on Trade and Development (UNCTAD)' to 'World Bank, United Nations Conference on Trade and Development, OECD DAC and national sources.'

**Comment by akmiller01** [comment]
We might actually need to have a think about how we cite data sources, and model them as their own thing. Right now the database configuration only allows for one source with one acronym.

**Comment by Duncan-Knox** [comment]
Ok. It's probably better to say something like 'multiple sources' or even the infamous 'development initiatives based on multiple sources' in this instance?

**Comment by akmiller01** [comment]
For the moment I can add multiple organisations to the source field, but in the future I'd like to expand it into it's own model. So if a user wants "all data by the OECD" for example, the database can fetch all data connected to the OECD element, rather than looking for the phrase "OECD" in a long string of other sources.

**Comment by Duncan-Knox** [comment]
Is this in reference to data sources or rows within data sources? Or both?

**Comment by akmiller01** [comment]
Specifically the `source` and `source_acronym` fields on the `Source` database model. I would want to spin those off into their own model, something like `SourceOrganisation` so that one data `Source` could have multiple `SourceOrganisation`s attached to it.

**Comment by Napho** [comment]
I think that would make a lot of sense
