### ISSUE TITLE
CRS

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/ddw-analyst-ui#79]
Hi @akmiller01 might be wrong but still seems tricky to manipulate data from this on the UI - I was wondering if you could please confirm the data is linking ok between front and back end? Also very minor point, is a name change from Common Reporting Standard to Creditor Reporting System at all possible?

**Comment by akmiller01** [comment]
Ah yeah, of course. Not sure how I got that acronym wrong.

**Comment by akmiller01** [comment]
Done!

**Comment by akmiller01** [comment]
Also can confirm the CRS is fine on the back-end. Is it just too big for the front-end to handle @edwinmp ?

**Comment by Duncan-Knox** [comment]
I narrowed down the criteria on a filter and select query and got output. Meaning it is there. There possibly is a point at which the request won't load on the export page if it is too large. I'll do more testing to see at what point this is.

**Comment by akmiller01** [comment]
Either the size, or perhaps the format one of the columns causes the data not to display (I'm thinking something large, or with weird formatting like Long Description).

**Comment by Duncan-Knox** [comment]
I got output from stripping columns out (including LD). I guess it may link to this. I think I've been able to get larger (by row and column count) extracts from the FTS without issue.

**Comment by Duncan-Knox** [comment]
Moving back to 'to do' as the source has been updated since the data was added onto the UI.

**Comment by Duncan-Knox** [comment]
Hi @akmiller01, in light of your comment at the launch on being able to update data, is it please possible for you to refresh the latest CRS data into the system. There's been an April update which moved 2016 price data into 2017 data, as well as other standard CRS updates. I expect we plan to use the newer CRS across a number of projects in the not too distant future and believe we'd benefit from having this updated data in the UI. I was wondering how much of a job it is to refresh the CRS system?

**Comment by akmiller01** [comment]
I can do it as soon as I get into the office. Should be done in less than
an hour with indexing.

**Comment by Duncan-Knox** [comment]
Nice, excellent and thanks!
