### ISSUE TITLE
Create user roles + permissions

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#8]
Define roles super admin, admin, analyst: 
* read
* write
* delete

**Comment by Napho** [comment]
@akmiller01  @edwinmp  isnt this already an inbuilt django-cms functionality?

**Comment by akmiller01** [comment]
The ability to create roles is in the Django CMS. Should we set up default ones?

**Comment by edwinmp** [comment]
Yup, hopefully with permissions... would love to have a way of manipulating permissions that doesn't go through the Django admin. Not now though... basic roles and permissions are fine.

We do need an endpoint that returns user information, including their role/permissions ... I'll need this for access control on the FE, and it should be a security layer on the API views (not sure if it's there by default)

**Comment by akmiller01** [comment]
Okay, so let's set up default roles and permissions as a part of this scope. What roles do we need? All I can think of at this point is "Admin" (someone with access to the backend, perhaps the ability to modify other's queries) and "User" (someone with write access to things they own, and read access to everything else).

**Comment by edwinmp** [comment]
Yup, that's fine... any other kind of access control (for ordinary users) can be managed via read/write/delete permissions to resources (I hope Django supports it).

**Comment by akmiller01** [comment]
If that's the case, @edwinmp , you should just be able to query the Knox API for `user.is_superuser` and we can skip the process of creating default roles altogether. Also, default admin permissions is pretty fine-grained: 
![image](https://user-images.githubusercontent.com/2836840/53813927-b0de9980-3f2c-11e9-9b91-d9701db09b5f.png)

**Comment by akmiller01** [comment]
Is this covered by #59? We just have Super admin and analyst, basically, but we might not need to complicate it further.
