### ISSUE TITLE
Non-grant government revenue in US$

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/ddw-analyst-ui#81]
Data available in current NCU, current US$, constant 2016 US$, constant 2017 US$.

Queries outstanding from Richard which may result in revisions to data.

[Non-grant government revenue.xlsx](https://github.com/devinit/ddw-analyst-ui/files/3117186/Non-grant.government.revenue.xlsx)

**Comment by Duncan-Knox** [comment]
Metadata sorry forgot to add @akmiller01. Would you like me to resend with a tab for metadata? 

Source is: IMF World Economic Outlook database and Article IV Staff and programme review reports (various).

**Comment by Duncan-Knox** [comment]
Although the detailed information on the source by individual country is I think available on the DDH in some capacity so in the end a user may be pointed to this more detailed sourcing document?

**Comment by akmiller01** [comment]
I should be fine without metadata for the moment. You can always make amendments to my meta later

**Comment by Duncan-Knox** [comment]
Added back into To do. ITEP data needs merging in where there are gaps in DDH data and any available updates could be added in to the version to be resubmitted.

**Comment by Duncan-Knox** [comment]
Hi @akmiller01, new version attached, Changes include gaps filled for Yemen, China and Tajikistan. Duplicates removed for two countries, Ready for loading when the time is right, Let me know if you need any follow up checks on processed versions. 

[Non-grant government revenue 08-05-2019.xlsx](https://github.com/devinit/ddw-analyst-ui/files/3157825/Non-grant.government.revenue.08-05-2019.xlsx)

**Comment by akmiller01** [comment]
Update here:

https://github.com/devinit/ddw-analyst-ui/blob/data_updates/data_updates/manual/CSV/non_grant_revenue.csv

**Comment by Duncan-Knox** [comment]
There's four duplicate values for Zimbabwe at the end. Possibly occurring in relation to my removal of four entries (for two other countries) from the version you previously had.

May it please be possible to edit column names from 'value_2016' to 'value_usd_constant_2016'/'value_usd_2016'? Same for 2017 constant usd column [edit].

No other issues spotted.

**Comment by akmiller01** [comment]
Fixed!
