### ISSUE TITLE
Optimize Postgre(Production) for read

### ISSUE THREAD

**Issue by Napho** [devinit/ddw-analyst-ui#85]

**Comment by akmiller01** [comment]
As discussed, this may include refactoring pagination code to swap Offset for Seek, and introducing count estimates instead of `count(*)`

**Comment by k8hughes** [comment]
@akmiller01 @wakibi is this issue relevant now or should we just close it?

**Comment by akmiller01** [comment]
No, looks like it was moved to Done but never closed.
