### ISSUE TITLE
DAC tables

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/ddw-analyst-ui#88]

**Comment by Duncan-Knox** [comment]
Hi @akmiller01 These are all using the latest update, which is great. The DAC states the data is in constant 2016 prices within the dataset when it is actually 2017 prices! Which is a bit of a nuisance, not sure what can be done our end though, I suspect they'll fix this on another update.

I'd suggest a couple of name changes on the UI, if you agree, I believe these are more commonly known.
'Official Development Assistance 1 (DAC1)' to 'OECD DAC 1'
'Official Development Assistance 2A (DAC2A)' to 'OECD DAC2A'
'Official Development Assistance 2B (DAC2B)' to 'OECD DAC2B'
'Official Development Assistance 5 (DAC5)' to 'OECD DAC5'

**Comment by akmiller01** [comment]
https://github.com/devinit/ddw-analyst-ui/pull/89/files
