### ISSUE TITLE
Firefox export csv bug

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#93]
When using firefox I have discovered that the esport cvs button doesn't work.
I discovered this when looking at the already saved queries for example this page:  http://138.68.138.212/queries/data/31 

No error code is showing in the console.

If this is hard to fix we could leave it out for now and tell users to start using hte app on Crome initially.  (not launch blocking)

**Comment by edwinmp** [comment]
@k8hughes I cannot replicate this. What's the Firefox version you're using? Once you take note of that, please try to update the browser (if it's not updated already) and test again.

**Comment by edwinmp** [comment]
I'm closing this since I cannot replicate it in the latest version of Firefox.
